"use client";

import { useState } from "react";
import { MOCK_SIGNALS } from "@/lib/signals";
import { Signal } from "@/types";
import { FileText, Download, ChevronDown, ChevronUp } from "lucide-react";

function generateReportContent(signals: Signal[], brief: string): string {
  const categories = [...new Set(signals.map((s) => s.category))];
  const strong = signals.filter((s) => s.strength === "strong");
  const emerging = signals.filter((s) => s.strength === "emerging");
  const weak = signals.filter((s) => s.strength === "weak");

  return `
## Executive Summary

${brief || "This report maps the current landscape of emerging technology signals with strategic implications for brands operating in fashion, beauty, lifestyle, and culture."}

Across ${signals.length} signals monitored, we identify ${strong.length} confirmed strong trends, ${emerging.length} emerging signals, and ${weak.length} early weak signals worth watching.

---

## Signal Landscape

**Categories covered:** ${categories.map((c) => c.replace("-", " ")).join(", ")}

${signals
  .map(
    (s) => `### ${s.title}
**Category:** ${s.category.replace("-", " ")} · **Strength:** ${s.strength}

${s.summary}

**Why it's emerging:** ${s.why_emerging}

**Brand relevance:** ${s.brand_relevance}

*Sources: ${s.sources.join(", ") || "Manual"} · Tags: ${s.tags.map((t) => `#${t}`).join(" ")}*
`
  )
  .join("\n---\n\n")}

---

## Strategic Recommendations

1. **Prioritise** the ${strong.length} strong signals for near-term brand activation — consumer awareness is building.
2. **Pilot** the ${emerging.length} emerging signals — invest in small experiments now before market saturation.
3. **Monitor** the ${weak.length} weak signals — these are the future-facing opportunities for 2–3 year horizon planning.

---

*Generated by Trend Radar — ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}*
`.trim();
}

export default function ReportsPage() {
  const [brief, setBrief] = useState("");
  const [selectedIds, setSelectedIds] = useState<string[]>(MOCK_SIGNALS.map((s) => s.id));
  const [report, setReport] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [showSignalPicker, setShowSignalPicker] = useState(false);

  const toggleSignal = (id: string) =>
    setSelectedIds((prev) =>
      prev.includes(id) ? prev.filter((x) => x !== id) : [...prev, id]
    );

  const generate = () => {
    setGenerating(true);
    setTimeout(() => {
      const selected = MOCK_SIGNALS.filter((s) => selectedIds.includes(s.id));
      setReport(generateReportContent(selected, brief));
      setGenerating(false);
    }, 800);
  };

  const download = () => {
    if (!report) return;
    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `trend-report-${Date.now()}.md`;
    a.click();
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-4xl mx-auto px-6 py-10">
        <div className="flex items-center justify-between mb-8">
          <div>
            <h1 className="text-2xl font-bold text-gray-900 mb-1">Report Builder</h1>
            <p className="text-sm text-gray-500">Generate a strategic brief from your selected signals.</p>
          </div>
          {report && (
            <button
              onClick={download}
              className="flex items-center gap-2 px-4 py-2 text-sm border rounded-lg hover:bg-gray-50 font-medium"
            >
              <Download size={15} />
              Export
            </button>
          )}
        </div>

        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-6 mb-6 space-y-5">
          <div>
            <label className="text-xs font-semibold text-gray-500 uppercase tracking-wide">
              Report brief / focus (optional)
            </label>
            <textarea
              rows={3}
              className="mt-1 w-full border rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 resize-none"
              placeholder="e.g. 'Strategic brief for a luxury beauty brand entering the biotech space in 2027'"
              value={brief}
              onChange={(e) => setBrief(e.target.value)}
            />
          </div>

          <div>
            <button
              className="flex items-center gap-2 text-xs font-semibold text-gray-500 uppercase tracking-wide hover:text-gray-800"
              onClick={() => setShowSignalPicker((v) => !v)}
            >
              {showSignalPicker ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
              Signals included ({selectedIds.length}/{MOCK_SIGNALS.length})
            </button>
            {showSignalPicker && (
              <div className="mt-3 grid grid-cols-1 sm:grid-cols-2 gap-2">
                {MOCK_SIGNALS.map((s) => (
                  <label key={s.id} className="flex items-start gap-2 cursor-pointer group">
                    <input
                      type="checkbox"
                      checked={selectedIds.includes(s.id)}
                      onChange={() => toggleSignal(s.id)}
                      className="mt-0.5 accent-indigo-600"
                    />
                    <span className="text-sm text-gray-700 group-hover:text-gray-900 leading-tight">
                      {s.title}
                    </span>
                  </label>
                ))}
              </div>
            )}
          </div>

          <button
            onClick={generate}
            disabled={generating || selectedIds.length === 0}
            className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-indigo-600 text-white rounded-xl hover:bg-indigo-700 font-semibold text-sm disabled:opacity-60"
          >
            <FileText size={16} />
            {generating ? "Generating report…" : "Generate report"}
          </button>
        </div>

        {report && (
          <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-8">
            <div className="prose prose-sm max-w-none">
              {report.split("\n").map((line, i) => {
                if (line.startsWith("### ")) return <h3 key={i} className="font-bold text-gray-900 mt-6 mb-1">{line.slice(4)}</h3>;
                if (line.startsWith("## ")) return <h2 key={i} className="font-bold text-gray-900 text-lg mt-8 mb-3 pb-2 border-b">{line.slice(3)}</h2>;
                if (line.startsWith("**") && line.endsWith("**")) return <p key={i} className="font-semibold text-gray-800 my-1">{line.slice(2, -2)}</p>;
                if (line.startsWith("---")) return <hr key={i} className="my-6 border-gray-100" />;
                if (line.match(/^\d+\./)) return <p key={i} className="text-sm text-gray-700 my-1.5 ml-4">{line}</p>;
                if (line.startsWith("*") && line.endsWith("*")) return <p key={i} className="text-xs text-gray-400 italic my-2">{line.slice(1, -1)}</p>;
                if (!line.trim()) return <div key={i} className="h-2" />;
                return <p key={i} className="text-sm text-gray-700 leading-relaxed my-1.5">{line}</p>;
              })}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
