import { Signal } from "@/types";

export const MOCK_SIGNALS: Signal[] = [
  // AI
  {
    id: "ai-1",
    title: "Generative AI in Fashion Design",
    summary: "Midjourney, Adobe Firefly and tools like Cala are entering the design pipeline — from mood boards to tech packs — compressing weeks of work into hours.",
    why_emerging: "Speed and cost pressure on design teams, plus a new generation of digitally-native designers who treat AI as a creative collaborator, not a threat.",
    brand_relevance: "Shifts the designer role from maker to director/curator. Opens questions about IP, authorship, and authenticity that brands will need to position on publicly.",
    category: "ai",
    strength: "strong",
    sources: ["Business of Fashion", "TechCrunch", "Hacker News"],
    tags: ["fashion", "ai", "design", "creative", "generative"],
    created_at: "2026-05-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    position: { x: 60, y: 70 },
  },
  {
    id: "ai-2",
    title: "AI Personal Stylists at Scale",
    summary: "Apps like Styled AI and Amazon's StyleSnap are moving from novelty to genuinely useful — learning body type, budget, occasion, and cultural context.",
    why_emerging: "LLM reasoning + multimodal vision finally makes context-aware styling advice possible without a human stylist in the loop.",
    brand_relevance: "Direct-to-wardrobe models, brand-specific style assistants, and personalised product discovery at a scale previously impossible.",
    category: "ai",
    strength: "emerging",
    sources: ["TechCrunch", "Vogue Business", "Product Hunt"],
    tags: ["fashion", "ai", "personalisation", "retail"],
    created_at: "2026-05-10T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    position: { x: 310, y: 28 },
  },
  {
    id: "ai-3",
    title: "Synthetic Models & Virtual Influencers",
    summary: "Brands like Levi's and H&M are using AI-generated models to diversify campaign imagery without additional photoshoots. Virtual influencers like Lil Miquela command millions of followers.",
    why_emerging: "Production costs, speed, and the ability to represent any body type, ethnicity, or style without logistics constraints.",
    brand_relevance: "Reduces campaign overhead but carries reputational risk if transparency is lacking. The 'who made this?' question is becoming central.",
    category: "ai",
    strength: "strong",
    sources: ["Vogue Business", "WWD", "The Verge"],
    tags: ["fashion", "ai", "marketing", "models", "virtual"],
    created_at: "2026-04-15T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    position: { x: 210, y: 230 },
  },

  // VR/AR
  {
    id: "ar-1",
    title: "AR Try-On Going Mainstream",
    summary: "Snap, Apple Vision Pro and standalone apps are normalising augmented reality for fashion and beauty try-on at scale. Major retailers are embedding it natively.",
    why_emerging: "Hardware costs falling + consumer comfort rising after COVID-era digital shopping habits normalised virtual interaction with products.",
    brand_relevance: "Reduces return rates, enables digital-first product launches, opens virtual showroom strategies for markets without physical retail presence.",
    category: "vr-ar",
    strength: "strong",
    sources: ["Product Hunt", "TechCrunch", "Snap Investor Reports"],
    tags: ["fashion", "ar", "retail", "digital", "ecommerce"],
    created_at: "2026-04-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    position: { x: 570, y: 55 },
  },
  {
    id: "ar-2",
    title: "Spatial Fashion Shows",
    summary: "Designers including Balenciaga and emerging houses are staging fashion shows in virtual and mixed reality environments, accessible globally via headset or phone.",
    why_emerging: "Apple Vision Pro ecosystem + declining cost of VR production tools. Solves the reach problem of physical runway shows.",
    brand_relevance: "Democratises runway access, enables interactive experiences, and creates digital collectibles from show moments.",
    category: "vr-ar",
    strength: "emerging",
    sources: ["Vogue Business", "Dezeen", "WWD"],
    tags: ["fashion", "vr", "runway", "experience", "luxury"],
    created_at: "2026-05-05T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    position: { x: 790, y: 30 },
  },

  // Wearables
  {
    id: "wear-1",
    title: "Health-Monitoring Smart Jewellery",
    summary: "Rings (Oura, Samsung Galaxy Ring), bracelets, and pendants that track sleep, stress, HRV, and cycle health are moving from wellness niche to mainstream accessory.",
    why_emerging: "Miniaturisation of sensors, longer battery life, and growing consumer appetite for continuous passive health data — without the clinical look of a smartwatch.",
    brand_relevance: "Luxury and fashion jewellery brands have a major entry point: beautiful health tech that competes on aesthetics first, function second.",
    category: "wearables",
    strength: "strong",
    sources: ["Wired", "MIT Tech Review", "Product Hunt"],
    tags: ["wellness", "jewellery", "health", "wearables", "luxury"],
    created_at: "2026-03-20T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    position: { x: 130, y: 370 },
  },
  {
    id: "wear-2",
    title: "Emotion-Responsive Clothing",
    summary: "Experimental garments that change colour, texture, or illumination in response to biometric signals — heart rate, skin conductance, body temperature.",
    why_emerging: "Soft electronics maturing, e-textile manufacturing scaling, and growing cultural interest in emotional transparency and self-expression through dress.",
    brand_relevance: "Early proof-of-concept territory for fashion houses wanting to lead in experiential and conceptual product. Strong press and editorial value.",
    category: "wearables",
    strength: "weak",
    sources: ["Dezeen", "MIT Media Lab", "arXiv"],
    tags: ["fashion", "emotion", "e-textiles", "innovation", "wearables"],
    created_at: "2026-05-18T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    position: { x: 390, y: 310 },
  },

  // Biotech
  {
    id: "bio-1",
    title: "Bioprinted Skin for Cosmetics Testing",
    summary: "Labs are printing human skin tissue to replace animal testing in beauty, with L'Oréal and startups like Poietis leading commercial adoption.",
    why_emerging: "EU animal testing bans + consumer demand for ethical beauty are compressing timelines. Cost-per-test is dropping below traditional alternatives.",
    brand_relevance: "Beauty and skincare brands can position bioprinting as a cruelty-free innovation story, not just compliance. A genuine point of difference.",
    category: "biotech",
    strength: "emerging",
    sources: ["arXiv", "Vogue Business", "MIT Tech Review"],
    tags: ["beauty", "biotech", "ethics", "skincare", "testing"],
    created_at: "2026-04-20T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    position: { x: 620, y: 340 },
  },
  {
    id: "bio-2",
    title: "Microbiome-Based Skincare",
    summary: "Brands like Mother Dirt, Gallinée, and AOBiome are building products around the skin's microbiome — probiotics, prebiotics, and live cultures in formulation.",
    why_emerging: "Gut microbiome science is migrating to skin science. Consumer familiarity with 'good bacteria' is creating a ready market.",
    brand_relevance: "Positions a brand in the credible intersection of science and natural beauty. Requires investment in dermatological research credibility.",
    category: "biotech",
    strength: "emerging",
    sources: ["bioRxiv", "WWD", "Allure"],
    tags: ["beauty", "skincare", "microbiome", "science", "wellness"],
    created_at: "2026-05-12T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    position: { x: 860, y: 280 },
  },
  {
    id: "bio-3",
    title: "Lab-Grown Leather & Materials",
    summary: "Mylo (Bolt Threads), Mycelium leather (Ecovative), and lab-grown animal leather (Modern Meadow) are moving from prototype to commercial scale.",
    why_emerging: "Multiple well-funded startups hitting production scale simultaneously. Hermès, Stella McCartney, and Adidas already partnering.",
    brand_relevance: "Genuine alternative to animal leather with a sustainability narrative that holds up to scrutiny. Premium pricing justified by novelty and ethics.",
    category: "biotech",
    strength: "emerging",
    sources: ["Dezeen", "Business of Fashion", "Wired"],
    tags: ["fashion", "materials", "sustainability", "leather", "biotech"],
    created_at: "2026-04-08T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    position: { x: 1070, y: 320 },
  },

  // 3D Printing
  {
    id: "3d-1",
    title: "3D-Printed Fashion at Scale",
    summary: "Designers like Iris van Herpen and startups like Zellerfeld are pushing 3D printing from couture novelty to scalable footwear and accessories manufacturing.",
    why_emerging: "Material breakthroughs — flexible filaments, recycled inputs, and multi-material printing — are solving the wearability problem that blocked previous waves.",
    brand_relevance: "On-demand, zero-waste production with aesthetic differentiation. Genuine sustainability story. Enables customisation at scale.",
    category: "3d-printing",
    strength: "emerging",
    sources: ["Dezeen", "Wired", "Kickstarter"],
    tags: ["fashion", "sustainability", "manufacturing", "footwear", "3d"],
    created_at: "2026-03-15T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    position: { x: 80, y: 590 },
  },
  {
    id: "3d-2",
    title: "Custom 3D-Printed Cosmetics",
    summary: "Startups and brands are developing 3D printers that dispense custom-blended foundation, lipstick, and skincare formulations on demand.",
    why_emerging: "Consumer demand for personalisation meeting accessible hardware. Foreo and Perfect365 already shipping consumer-facing devices.",
    brand_relevance: "Transforms beauty retail from product to service. Brands own the formulation IP and subscription refill model rather than physical product.",
    category: "3d-printing",
    strength: "weak",
    sources: ["TechCrunch", "Allure", "Product Hunt"],
    tags: ["beauty", "personalisation", "3d", "innovation", "retail"],
    created_at: "2026-05-20T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    position: { x: 330, y: 630 },
  },

  // Robotics
  {
    id: "robot-1",
    title: "Robotic Retail Fulfilment",
    summary: "Warehouse and last-mile robotics from Ocado, Amazon, and startups are reshaping what fast fashion and luxury fulfilment can look like.",
    why_emerging: "Labour costs and speed expectations converging. Same-day luxury delivery is becoming a consumer expectation rather than a premium.",
    brand_relevance: "Enables new service promises — personalised same-day packaging, kitting, monogramming at fulfilment stage without manual overhead.",
    category: "robotics",
    strength: "strong",
    sources: ["Wired", "McKinsey Reports", "TechCrunch"],
    tags: ["retail", "logistics", "robotics", "luxury", "operations"],
    created_at: "2026-04-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    position: { x: 580, y: 570 },
  },

  // Materials
  {
    id: "mat-1",
    title: "Programmable & Shape-Shifting Textiles",
    summary: "MIT and commercial labs are developing fabrics that change shape, porosity, or insulation in response to temperature, moisture, or electrical input.",
    why_emerging: "Decades of research in smart textiles converging with cheaper manufacturing and fashion's appetite for functional innovation.",
    brand_relevance: "Performance and outdoor brands have the most immediate applications. Luxury houses can use for conceptual seasonal storytelling.",
    category: "materials",
    strength: "weak",
    sources: ["MIT Tech Review", "arXiv", "Dezeen"],
    tags: ["textiles", "innovation", "materials", "smart", "fashion"],
    created_at: "2026-05-15T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    position: { x: 840, y: 610 },
  },
  {
    id: "mat-2",
    title: "Carbon-Negative Fashion Materials",
    summary: "Algae-based fibres (Algaeing), carbon-captured textiles (AirCarbon by Newlight), and seaweed yarns are achieving commercial viability.",
    why_emerging: "Net-zero commitments from major fashion groups are creating demand that didn't exist 3 years ago. Materials science catching up.",
    brand_relevance: "Genuine sustainability differentiation that goes beyond recycling. Allows brands to move from 'less bad' to 'actively good' positioning.",
    category: "materials",
    strength: "emerging",
    sources: ["Business of Fashion", "Dezeen", "Fast Company"],
    tags: ["sustainability", "materials", "fashion", "climate", "innovation"],
    created_at: "2026-04-25T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    position: { x: 1080, y: 570 },
  },

  // Spatial Computing
  {
    id: "spatial-1",
    title: "Digital Fashion & NFT Wearables",
    summary: "Virtual garments worn on social media, in games, and in spatial environments — from DressX drops to Fortnite collaborations with luxury houses.",
    why_emerging: "Gen Z identity formation happening increasingly in digital spaces. Brands that aren't present in gaming and virtual worlds are invisible to a generation.",
    brand_relevance: "New revenue stream, new audience touchpoint, and a way to experiment with radical design without physical production costs.",
    category: "spatial-computing",
    strength: "emerging",
    sources: ["Business of Fashion", "Vogue Business", "Wired"],
    tags: ["fashion", "digital", "nft", "gaming", "virtual", "gen-z"],
    created_at: "2026-05-01T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    position: { x: 60, y: 840 },
  },
  {
    id: "spatial-2",
    title: "Spatial Commerce & Immersive Retail",
    summary: "Apple Vision Pro and Meta Quest are enabling fully immersive shopping environments — virtual flagship stores, 3D product inspection, and social shopping.",
    why_emerging: "Headset adoption crossing early adopter threshold. Brands like Net-a-Porter and Nike building spatial commerce experiences.",
    brand_relevance: "Opportunity to create brand worlds rather than brand pages. Flagship store experience without geographic limits.",
    category: "spatial-computing",
    strength: "emerging",
    sources: ["Vogue Business", "TechCrunch", "Dezeen"],
    tags: ["retail", "spatial", "vr", "commerce", "luxury"],
    created_at: "2026-05-08T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    position: { x: 310, y: 800 },
  },

  // Neurotech
  {
    id: "neuro-1",
    title: "Neurocosmetics: Mood-Responsive Beauty",
    summary: "Brands are developing products that interact with the nervous system — adaptogens, stress-responsive formulations, and EEG-informed skincare.",
    why_emerging: "Intersection of wellness culture, neuroscience research, and the ingredient transparency movement. Consumers increasingly literate in mind-body connection.",
    brand_relevance: "Opens an entirely new category: beauty that responds to mental state, not just skin type. Requires credible science partnership.",
    category: "neurotech",
    strength: "weak",
    sources: ["bioRxiv", "Vogue Business", "WWD"],
    tags: ["beauty", "wellness", "neuroscience", "innovation", "skincare"],
    created_at: "2026-05-22T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    position: { x: 570, y: 860 },
  },
  {
    id: "neuro-2",
    title: "Brain-Computer Interfaces in Consumer Tech",
    summary: "Neuralink, Synchron, and consumer-grade EEG headbands (Muse, Emotiv) are building the foundation for thought-controlled interfaces in everyday life.",
    why_emerging: "FDA approvals accelerating. Consumer-grade BCI hardware improving dramatically. Cultural conversation normalising neurotechnology.",
    brand_relevance: "5-year horizon: controlling environments, shopping, and entertainment through thought. Fashion and beauty brands should understand the implications early.",
    category: "neurotech",
    strength: "weak",
    sources: ["MIT Tech Review", "Wired", "arXiv"],
    tags: ["neurotech", "bci", "future", "technology", "lifestyle"],
    created_at: "2026-05-30T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    position: { x: 820, y: 820 },
  },

  // Other / Cultural
  {
    id: "cult-1",
    title: "Longevity Culture & Anti-Ageing Tech",
    summary: "Bryan Johnson's Blueprint protocol, longevity clinics, and senolytics are mainstreaming the idea that ageing is a problem technology can solve — not just slow.",
    why_emerging: "Billionaire experimentation creating cultural permission for extreme wellness behaviours. Gen X and Millennial consumer interest spiking.",
    brand_relevance: "Luxury wellness, beauty, and lifestyle brands have a massive opportunity in credible longevity positioning — beyond anti-ageing cream marketing.",
    category: "other",
    strength: "emerging",
    sources: ["Wired", "MIT Tech Review", "Bloomberg"],
    tags: ["wellness", "longevity", "beauty", "health", "lifestyle", "culture"],
    created_at: "2026-04-10T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    position: { x: 1090, y: 800 },
  },
  {
    id: "cult-2",
    title: "Solarpunk Aesthetics & Eco-Futurism",
    summary: "A cultural movement imagining a positive ecological future — blending technology with nature, communal living, and optimistic climate narratives — is entering mainstream fashion and design.",
    why_emerging: "Climate anxiety fatigue creating appetite for positive futures. Solarpunk has moved from niche Tumblr subculture to major design awards and brand campaigns.",
    brand_relevance: "An aesthetic and values framework brands can authentically adopt — but requires genuine sustainability credentials or it reads as greenwashing.",
    category: "other",
    strength: "emerging",
    sources: ["Dezeen", "i-D Magazine", "Reddit r/solarpunk"],
    tags: ["culture", "aesthetics", "sustainability", "fashion", "design"],
    created_at: "2026-05-14T00:00:00Z",
    updated_at: "2026-06-01T00:00:00Z",
    position: { x: 190, y: 1070 },
  },
];

// Predefined edges showing signal relationships
export const SIGNAL_EDGES = [
  { id: "e1", source: "ai-1", target: "ai-2", label: "enables" },
  { id: "e2", source: "ai-3", target: "spatial-1", label: "intersects" },
  { id: "e3", source: "bio-1", target: "bio-2", label: "related" },
  { id: "e4", source: "bio-3", target: "mat-2", label: "adjacent" },
  { id: "e5", source: "ar-1", target: "spatial-2", label: "converging" },
  { id: "e6", source: "wear-1", target: "neuro-1", label: "intersects" },
  { id: "e7", source: "3d-1", target: "mat-1", label: "enables" },
  { id: "e8", source: "cult-1", target: "neuro-2", label: "adjacent" },
  { id: "e9", source: "spatial-1", target: "spatial-2", label: "related" },
  { id: "e10", source: "cult-2", target: "mat-2", label: "aligns" },
];

export const SIGNAL_TEMPLATES = [
  {
    label: "Emerging Technology",
    defaults: {
      category: "other" as const,
      strength: "weak" as const,
      summary: "Describe what this technology is and where it stands today.",
      why_emerging: "What forces are driving this forward — regulatory, economic, cultural, or scientific?",
      brand_relevance: "What does this mean for brands in fashion, beauty, or lifestyle?",
      tags: ["technology", "emerging"],
    },
  },
  {
    label: "Cultural Shift",
    defaults: {
      category: "other" as const,
      strength: "emerging" as const,
      summary: "Describe the cultural behaviour, belief, or aesthetic that is shifting.",
      why_emerging: "What generational, social, or media forces are amplifying this?",
      brand_relevance: "Which consumer segments does this affect and how should brands respond?",
      tags: ["culture", "behaviour"],
    },
  },
  {
    label: "Material Innovation",
    defaults: {
      category: "materials" as const,
      strength: "weak" as const,
      summary: "Describe the new material and its current state of development.",
      why_emerging: "What has changed technically or commercially to make this viable now?",
      brand_relevance: "Which product categories or brand values does this material enable?",
      tags: ["materials", "innovation", "sustainability"],
    },
  },
];

export function getSignalColor(category: Signal["category"] | undefined): string {
  const colors: Record<string, string> = {
    ai: "#6366f1",
    "vr-ar": "#8b5cf6",
    wearables: "#ec4899",
    biotech: "#10b981",
    "3d-printing": "#f59e0b",
    robotics: "#3b82f6",
    materials: "#14b8a6",
    "spatial-computing": "#a855f7",
    neurotech: "#f43f5e",
    other: "#6b7280",
  };
  return colors[category ?? "other"] ?? "#6b7280";
}

export function getStrengthLabel(strength: Signal["strength"] | undefined): string {
  return ({ weak: "Weak signal", emerging: "Emerging", strong: "Strong" } as Record<string, string>)[strength ?? "weak"] ?? "Weak signal";
}

export function getStrengthBadgeStyle(strength: Signal["strength"] | undefined): string {
  return ({
    weak: "bg-gray-100 text-gray-600",
    emerging: "bg-amber-50 text-amber-700",
    strong: "bg-green-50 text-green-700",
  } as Record<string, string>)[strength ?? "weak"] ?? "bg-gray-100 text-gray-600";
}
