import { Trend, Signal } from "@/types";

export const TRENDS: Trend[] = [
  {
    id: "ai-creativity",
    name: "The Machine That Replaced Your Moodboard",
    description: "AI isn't a tool anymore — it's a creative collaborator that designs faster, cheaper, and stranger than any human team. Fashion is only beginning to reckon with what that means.",
    color: "#FF2D78",
    relevanceScore: 89,
    redditQuery: "AI fashion design generative",
    newsQuery: "AI generative fashion design",
    position: { x: 520, y: 380 },
    whyRelevant: "AI is compressing creative cycles by 10x. Brands that don't integrate AI into design, forecasting, and campaigns will be out-produced by those that do. The competitive advantage is structural, not marginal — it compounds every quarter.",
    trajectory: "Over the next 18 months, AI moves from creative augmentation to creative autonomy. The debate shifts from 'should we use AI' to 'who owns the output' and 'how do we maintain brand authenticity'. Brands that build proprietary AI training sets from their own archives will command a meaningful moat. Expect the first major AI-only fashion label to debut by 2027.",
    nextSteps: [
      "Audit which creative workflows can be AI-augmented this quarter and run a 30-day pilot",
      "Test one AI-generated campaign concept with a controlled consumer group and measure recall vs. traditional creative",
      "Draft an AI ethics policy covering synthetic models, attribution, and data provenance before regulation forces your hand",
    ],
    macroContext: "Three forces collided: post-pandemic cost pressure collapsed creative budgets forcing brands to find efficiency, GPU costs fell 10x making generative AI accessible to any studio, and Gen Z designers entered the workforce already AI-native. The result isn't a tool upgrade — it's a generational shift in who gets to be creative and what creative labour is worth.",
  },
  {
    id: "digital-identity",
    name: "Dressing the Self You Are Online",
    description: "Your avatar's outfit matters as much as what you wore to dinner. Digital fashion, virtual personas, and online self-expression are becoming billion-dollar identity markets.",
    color: "#FFE600",
    relevanceScore: 63,
    redditQuery: "digital identity avatar virtual fashion",
    newsQuery: "digital identity virtual avatar fashion",
    position: { x: 1100, y: 220 },
    whyRelevant: "The next generation measures social status as much by digital appearance as physical. Brands that only exist physically are invisible to the demographic most likely to drive culture for the next 20 years. Digital drops carry zero inventory risk.",
    trajectory: "Digital identity consolidates around 2–3 cross-platform standards (Ready Player Me, Open Metaverse ID) making digital wardrobes persistent across gaming, work, and social. Fashion's digital revenue goes from experimental to budget line by 2027. The first luxury house to offer a full digital twin wardrobe with every physical purchase will own the format.",
    nextSteps: [
      "Map your brand's current presence (or absence) across Roblox, Fortnite, and Ready Player Me",
      "Commission one digital-only drop to test virtual commerce mechanics without physical production risk",
      "Study how gaming fashion economics differ from physical — scarcity, resale, and community dynamics all work differently",
    ],
    macroContext: "Two years of pandemic-enforced digital life accelerated a psychological shift that was already underway — online space started to feel as real as physical. Combined with Gen Z having grown up inside gaming worlds where avatar = self since age 8, and the economic reality that digital goods carry zero inventory risk and infinite margin, brands had no choice but to follow attention. The cultural shift came first; the commerce followed.",
  },
  {
    id: "ar-commerce",
    name: "Try Before You Never Buy",
    description: "AR try-on is collapsing the distance between desire and purchase. Virtual fitting rooms are cutting returns, lifting conversion, and making physical retail look slow.",
    color: "#7B2FFF",
    relevanceScore: 55,
    redditQuery: "AR VR shopping try-on retail",
    newsQuery: "augmented reality virtual try-on shopping",
    position: { x: 1700, y: 380 },
    whyRelevant: "AR try-on is already delivering measurable ROI — 30–50% lower returns, 2–3x higher conversion. It's no longer experimental. Brands without it are at a structural conversion disadvantage, especially as mobile AR becomes the default browsing behaviour.",
    trajectory: "AR try-on becomes table stakes for e-commerce within 24 months — similar to how product photography was once optional. The next phase is social AR: outfit try-on directly in Instagram and TikTok stories before purchase. Brands that build AR asset libraries now will be significantly ahead when the platforms mandate it.",
    nextSteps: [
      "Integrate AR try-on SDK into product pages for your top 20 SKUs and track return rates before/after",
      "Brief your wholesale buyers on virtual showroom capabilities — 40% already prefer virtual to physical visits",
      "Test AR-first product reveals in campaign launches to measure pre-purchase engagement",
    ],
    macroContext: "Three separate forces converged: smartphones finally became powerful enough for real-time 3D AR in 2022, platforms commoditised AR distribution so brands didn't need to build it themselves, and post-pandemic consumers became genuinely uncomfortable with purchase uncertainty after a decade of rising return costs. AR didn't arrive because the tech was ready — it arrived because 38% return rates became existential for retail economics.",
  },
  {
    id: "biotech-beauty",
    name: "The Lab Is the New Beauty Counter",
    description: "Bioprinted skin. Microbiome formulas. Fermentation actives. The beauty industry is becoming a biotech industry — and the brands that understand biology will win.",
    color: "#00FF87",
    relevanceScore: 77,
    redditQuery: "biotech skincare microbiome beauty science",
    newsQuery: "biotech beauty skincare innovation",
    position: { x: 280, y: 900 },
    whyRelevant: "Consumer sophistication about ingredients is accelerating faster than most brands' R&D cycles. The brands that own efficacy narratives backed by biology command 3–5x premium pricing. Biotech is now table stakes for prestige positioning.",
    trajectory: "Biotech beauty splits into two tracks: mass-market microbiome (already arriving) and ultra-premium regenerative ingredients (exosomes, lab-grown collagen). By 2028, a biologically credentialed product range — with peer-reviewed data — becomes the minimum requirement for prestige positioning. Brands without clinical evidence will compete only on price.",
    nextSteps: [
      "Audit your ingredient portfolio against microbiome, postbiotic, and exosome pipelines — identify one to pilot in the next NPD cycle",
      "Commission an independent clinical study on a hero ingredient; peer-reviewed data is the new minimum for prestige credibility",
      "Map the regulatory status of your most innovative ingredients in key markets (EU, US, South Korea)",
    ],
    macroContext: "The gut health revolution of the 2010s trained an entire consumer generation in microbiome literacy — they already understood 'good bacteria'. K-beauty's global spread introduced fermentation as a premium skincare concept. Post-pandemic, mental and physical health collapsed into a single priority. And regulatory pressure from the EU on efficacy claims forced brands to back science with evidence. Ingredient-literate consumers and regulation together are pulling beauty into biology.",
  },
  {
    id: "sustainable-materials",
    name: "Fashion Made From Air and Fungus",
    description: "Mycelium leather. Algae fibre. Carbon-captured nylon. A generation of radical materials is replacing conventional inputs — and making sustainability a design advantage, not a compromise.",
    color: "#FF6B35",
    relevanceScore: 68,
    redditQuery: "sustainable fashion materials mycelium algae",
    newsQuery: "sustainable bio-materials fashion innovation",
    position: { x: 900, y: 980 },
    whyRelevant: "EU Digital Product Passport regulation makes material traceability mandatory for all fashion sold in Europe from 2027. Brands caught greenwashing face fines up to €4M. The sustainable materials story must become supply-chain fact, not marketing copy.",
    trajectory: "The EU DPP deadline forces a materials reckoning in 2026–27. Brands that have already piloted alternative materials will pivot to scale; late movers will pay premium prices for constrained bio-material supply. Mycelium, algae, and carbon-captured fibres transition from niche to premium mainstream. The brands that own their material story own the premium consumer.",
    nextSteps: [
      "Begin lifecycle analysis (LCA) for your top 5 materials before DPP compliance becomes mandatory in 2027",
      "Pilot one alternative material in a limited collection to test consumer response and supply chain viability",
      "Audit your supplier tier 2 and tier 3 data — most brands can't answer basic DPP questions about their own supply chains",
    ],
    macroContext: "EU regulation is the primary force — the 2027 Digital Product Passport mandate turned sustainability from voluntary ethics into a legal compliance deadline. Secondary forces: Gen Z's documented willingness to pay a premium for environmental credibility, and post-pandemic supply chain trauma making brands rethink material origins for resilience reasons as much as sustainability ones. The market moved when the regulation gave it no alternative.",
  },
  {
    id: "3d-printing",
    name: "The Printer That Ate the Factory",
    description: "Zero inventory. No waste. Shoes in 45 minutes. 3D printing is rewriting the rules of fashion manufacturing — and the brands piloting it now are building an insurmountable lead.",
    color: "#00D4FF",
    relevanceScore: 44,
    redditQuery: "3D printing fashion footwear manufacturing",
    newsQuery: "3D printing fashion manufacturing",
    position: { x: 1500, y: 960 },
    whyRelevant: "3D printing solves fashion's two most expensive problems: overstock and speed-to-market. Early movers building IP in printable design accumulate a manufacturing and creative lead that compounds. The technology window for first-mover advantage is 18–36 months.",
    trajectory: "3D printing moves from couture novelty to accessories mainstream within 3 years. Footwear is the beachhead — Zellerfeld and New Balance are proving it works at scale. The next category is jewellery, then eyewear. On-demand local printing eliminates the global shipping model for small-batch products. Consumer-facing home printing for accessories becomes real by 2028.",
    nextSteps: [
      "Identify one product category (accessories, footwear, eyewear) for a 3D printing pilot and commission a cost comparison",
      "Explore IP ownership structure for your digital design files — this is the new product archive",
      "Connect with Zellerfeld, Stratasys, or EOS for a design collaboration conversation",
    ],
    macroContext: "Supply chain collapse during the pandemic exposed the fragility of the 8,000-mile manufacturing model — brands learned that concentration kills. 3D printing offers geographic independence: print anywhere, ship nothing. Simultaneously, flexible polymer advances in 2022–23 finally solved the wearability problem that blocked fashion applications for a decade. Economic pressure and material science solved two different problems at the same time.",
  },
  {
    id: "wearables",
    name: "Your Body Is Now a Dashboard",
    description: "Rings, patches, and smart fabrics are turning health data into a continuous stream. The question isn't whether consumers will wear health tech — it's whether fashion brands will design it.",
    color: "#0066FF",
    relevanceScore: 80,
    redditQuery: "smart wearables health ring fitness tracker",
    newsQuery: "smart wearables health monitoring",
    position: { x: 1950, y: 820 },
    whyRelevant: "Health data is becoming a lifestyle accessory. Fashion brands that design beautiful wearable hardware will own a category that tech companies cannot win on aesthetics alone. The market is open and the consumer demand signal is unambiguous.",
    trajectory: "The wearables market bifurcates: tech-led (Apple, Samsung, Google) competing on capability, and fashion-led competing on aesthetics and identity. Fashion's window to enter the category before tech brands solve the aesthetics problem is closing — 2–3 years at most. Smart fabrics democratise health sensing beyond devices and into everyday garments by 2028.",
    nextSteps: [
      "Commission consumer research: would your customer wear a health-tracking piece from your brand, and at what price point?",
      "Identify 2–3 health sensor companies for a co-design conversation on embedding sensors in existing product lines",
      "Study the Ray-Ban Meta case study — the lesson is 'fashion-first, tech-second' and it's directly applicable",
    ],
    macroContext: "Apple Watch normalised health data as a daily habit for 100M people before any fashion brand noticed. COVID made personal health metrics feel urgent and status-worthy simultaneously — a rare combination. And culturally, the shift from 'performance' identity to 'longevity' identity expanded the wearables audience from athletes to everyone. The aesthetic gap between medical device and luxury accessory is now the obvious white space.",
  },
  {
    id: "neurotech",
    name: "Skincare for Your Nervous System",
    description: "Adaptogens in your serum. EEG-validated ingredients. Brain-computer interfaces on the horizon. Neurotechnology is quietly redefining what beauty and wellness products are supposed to do.",
    color: "#FF00C1",
    relevanceScore: 38,
    redditQuery: "neurotech BCI brain computer interface wellness",
    newsQuery: "neurotech consumer brain computer interface",
    position: { x: 460, y: 1480 },
    whyRelevant: "Neurotech is 3–7 years from consumer mainstream, but the brands that build literacy now will set the category agenda. Neurocosmetics, stress-responsive products, and biofeedback beauty are all nascent but growing at 40%+ annually.",
    trajectory: "Neurotech moves from wellness niche to beauty category within 5 years. The path: adaptogen-infused topicals now → EEG-validated stress-response formulas by 2027 → wearable-integrated skincare by 2029. The first brand to credibly combine biometric feedback with a skincare product will own a premium category for a decade.",
    nextSteps: [
      "Brief your R&D team on neurocosmetics ingredients (ashwagandha, l-theanine, lion's mane) and their regulatory status",
      "Monitor Neuralink and consumer BCI timelines quarterly — build an internal briefing document now",
      "Map the overlap between your customer's wellness routines and stress management — this is the entry point",
    ],
    macroContext: "Pandemic anxiety created mass-market demand for stress management at scale that the wellness industry couldn't meet with existing products. The Calm and Headspace generation learned to think of mental health as something actively managed — not just something that happens. Meanwhile, biohacking culture shifted from fringe Reddit to mainstream with Huberman's 8M subscribers. Neurocosmetics is the inevitable product category at the collision of these two trends.",
  },
  {
    id: "spatial-computing",
    name: "Shopping in a World That Doesn't Exist Yet",
    description: "Spatial commerce isn't the metaverse hype cycle — it's the quiet infrastructure being built right now inside Vision Pro apps and virtual showrooms. First-movers will own the format.",
    color: "#C8FF00",
    relevanceScore: 50,
    redditQuery: "spatial computing Apple Vision Pro metaverse",
    newsQuery: "spatial computing Apple Vision Pro brands",
    position: { x: 1100, y: 1500 },
    whyRelevant: "Spatial commerce is the next retail format. Brands establishing presence in Vision Pro and Galaxy XR now will own brand recall when devices reach mass market. Net-a-Porter is already reporting 3x conversion vs. its standard app in spatial.",
    trajectory: "Spatial computing reaches the mass market tipping point in 2026–27 as Samsung Galaxy XR drives Android adoption and Vision Pro Gen 2 drops to sub-$2K. Fashion becomes the anchor category for spatial retail — the 'try-on room' killer app that justifies headset ownership. Brands with spatial presence in 2025 will have a 2–3 year head start on those that wait.",
    nextSteps: [
      "Greenlight a Vision Pro brand experience — even a minimal one — within the next 6 months",
      "Assign one person to monitor spatial platform developments and circulate a monthly briefing",
      "Brief your 3D/design team on the additional requirements for spatial content vs. standard e-commerce assets",
    ],
    macroContext: "Apple's Vision Pro legitimised spatial computing as a serious platform — not another Google Glass. The deeper driver is B2B workflow adoption (architects, surgeons, engineers) building the infrastructure that will eventually serve consumers. And fashion has a specific structural advantage: the try-on use case is the killer app that justifies headset ownership for mainstream consumers. Fashion is the pull force that makes spatial computing worth buying.",
  },
  {
    id: "longevity",
    name: "The Business of Never Getting Old",
    description: "Longevity isn't a niche biohacking obsession anymore — it's a mainstream cultural obsession with a $600B market attached. Every beauty, wellness, and lifestyle brand needs a position on it.",
    color: "#FF3333",
    relevanceScore: 91,
    redditQuery: "longevity anti-aging biohacking health",
    newsQuery: "longevity anti-ageing culture wellness",
    position: { x: 1750, y: 1460 },
    whyRelevant: "Longevity has moved from biohacker niche to mainstream with 400K-strong Reddit communities and Andrew Huberman at 8M YouTube subscribers. Every beauty, wellness, and lifestyle brand now competes in the longevity space whether they know it or not.",
    trajectory: "Longevity becomes the defining consumer category of the late 2020s — bigger than 'wellness' was in the 2010s. The convergence of biological age testing, GLP-1 body recomposition, and longevity clinics creates a new premium health consumer with significant disposable income. Beauty brands that don't reframe around longevity by 2026 will find their anti-ageing positioning feels anachronistic.",
    nextSteps: [
      "Reframe your brand's core product benefits through a longevity lens — 'protection', 'restoration', and 'biological age' are the new positioning vocabulary",
      "Commission consumer research on how your customer thinks about ageing, health optimisation, and biological vs. chronological age",
      "Identify one longevity clinic group or community for a strategic partnership — these are the new luxury wellness channels",
    ],
    macroContext: "The Ozempic/GLP-1 moment changed everything — not because of weight loss, but because it proved that biology could be intentionally modified for lifestyle benefits, and millions of ordinary people were willing to try. Combined with Bryan Johnson's viral $2M/year protocol making longevity aspirational rather than academic, and Huberman Lab creating a mass audience literate in the research, longevity became the dominant consumer health narrative of the late 2020s. The money followed the attention.",
  },
];

export const SIGNALS: Signal[] = [
  // ─── AI & Generative Creativity ───────────────────────────────────────────
  {
    id: "ai-s1", trendId: "ai-creativity",
    title: "okay so brands are now doing their entire moodboard with AI in like an afternoon",
    summary: "Major fashion houses are using Midjourney and Adobe Firefly to generate seasonal mood boards and concept visuals, compressing 3-week creative processes into hours.",
    source: "news", sourceName: "Business of Fashion", sourceUrl: "https://businessoffashion.com",
    date: "2026-05-12", crossLinks: ["did-s2", "did-s4"],
  },
  {
    id: "ai-s2", trendId: "ai-creativity",
    title: "H&M and Levi's campaigns literally don't have real models in them anymore",
    summary: "H&M and Levi's are deploying AI-generated models to diversify campaign imagery without photoshoots. Raises major questions around transparency and authenticity that neither brand has fully addressed.",
    source: "news", sourceName: "Vogue Business", sourceUrl: "https://voguebusiness.com",
    date: "2026-04-28", crossLinks: ["did-s1"],
  },
  {
    id: "ai-s3", trendId: "ai-creativity",
    title: "apparently you can go from a creative brief to a full tech pack with no human in between now",
    summary: "Cala's AI takes a concept brief and outputs production-ready tech packs. Early adopters report 60% faster development cycles — the product development pipeline is being fundamentally compressed.",
    source: "hackernews", sourceName: "Hacker News", sourceUrl: "https://news.ycombinator.com",
    date: "2026-05-20", crossLinks: [],
  },
  {
    id: "ai-s4", trendId: "ai-creativity",
    title: "junior designers are genuinely freaking out about AI taking their jobs and tbh it's not irrational",
    summary: "r/femalefashionadvice and r/malefashionadvice show growing anxiety among junior designers about AI replacing entry-level creative roles. The fear is specific and widely shared — this is an industry labour signal.",
    source: "reddit", sourceName: "r/femalefashionadvice", sourceUrl: "https://reddit.com/r/femalefashionadvice",
    date: "2026-06-01", crossLinks: [],
  },
  {
    id: "ai-s5", trendId: "ai-creativity",
    title: "there are apps predicting what's going to trend six months out and WGSN is not okay",
    summary: "Heuritech and Trendalytics use computer vision on social media to predict microtrends 6 months out. The traditional forecasting agency model — expensive, slow, human — is under structural threat.",
    source: "news", sourceName: "WWD", sourceUrl: "https://wwd.com",
    date: "2026-05-08", crossLinks: ["did-s3"],
  },
  {
    id: "ai-s6", trendId: "ai-creativity",
    title: "vogue published a fashion film that was completely AI generated and you honestly can't tell",
    summary: "OpenAI's Sora is being used by independent directors to produce fashion short films at near-zero budget. A Vogue-published film was entirely AI-generated — the format has crossed into editorial legitimacy.",
    source: "news", sourceName: "Vogue", sourceUrl: "https://vogue.com",
    date: "2026-05-30", crossLinks: [],
  },
  {
    id: "ai-s7", trendId: "ai-creativity",
    title: "designers are using AI to generate hundreds of colourways in an afternoon instead of spending weeks on it",
    summary: "Fashion studios are using Adobe Firefly's vector generation to produce print patterns and colourways in bulk. What took weeks of manual artwork now takes an afternoon — the design team's role is shifting from maker to curator.",
    source: "hackernews", sourceName: "Hacker News", sourceUrl: "https://news.ycombinator.com",
    date: "2026-06-09", crossLinks: ["ai-s3"],
  },
  {
    id: "ai-s8", trendId: "ai-creativity",
    title: "200 designers are suing AI companies for basically using their work to train on without asking",
    summary: "A coalition of 200 independent fashion designers filed a class action suit against Stability AI. This is the landmark IP case that will define AI's relationship with creative ownership — every brand using AI creative tools has a stake in the outcome.",
    source: "news", sourceName: "The Guardian", sourceUrl: "https://theguardian.com",
    date: "2026-06-11", crossLinks: [],
  },
  {
    id: "ai-s9", trendId: "ai-creativity",
    title: "brands doing virtual sampling in AI are spending 70% less on development which is kind of insane",
    summary: "Brands using AI to generate and approve colourways virtually before physical sampling report 70% cost savings. Physical strike-offs are becoming the exception — a structural shift in how fashion products are developed.",
    source: "news", sourceName: "Business of Fashion", sourceUrl: "https://businessoffashion.com",
    date: "2026-05-03", crossLinks: ["sus-s3"],
  },
  {
    id: "ai-s10", trendId: "ai-creativity",
    title: "fashion students at Parsons are submitting AI portfolios now and the schools don't know what to do",
    summary: "Gen Z designers are AI-native from day one. Students at Parsons and CSM are submitting AI-generated portfolios. Educators are split on whether to embrace or ban. The generation has already decided.",
    source: "reddit", sourceName: "r/fashiondesign", sourceUrl: "https://reddit.com/r/fashiondesign",
    date: "2026-06-13", crossLinks: ["ai-s4"],
  },
  {
    id: "ai-s11", trendId: "ai-creativity",
    title: "CLO 3D just auto-writes your construction notes for you now — the tech designer role is changing fast",
    summary: "CLO 3D's AI assistant auto-generates construction notes, BOM, and tolerances from a 3D garment. The technical designer role is being fundamentally redefined from execution to oversight.",
    source: "hackernews", sourceName: "Hacker News", sourceUrl: "https://news.ycombinator.com",
    date: "2026-04-17", crossLinks: [],
  },
  {
    id: "ai-s12", trendId: "ai-creativity",
    title: "there are AI fashion accounts with no human behind them hitting 10 million followers",
    summary: "AI-only fashion accounts (@AIRunway, @NeuralCouture) generate daily AI looks and are outperforming human creator accounts in engagement. The influencer category has a new entrant — one with zero overhead.",
    source: "reddit", sourceName: "r/artificial", sourceUrl: "https://reddit.com/r/artificial",
    date: "2026-06-02", crossLinks: ["did-s5"],
  },
  {
    id: "ai-s13", trendId: "ai-creativity",
    title: "Midjourney is now so realistic people are returning clothes because the real thing looks different from the AI photo",
    summary: "Midjourney v7's fabric simulation is photorealistic enough to fool buyers. First reports of returns triggered by AI-generated product imagery are appearing — a new liability category for e-commerce brands.",
    source: "news", sourceName: "Wired", sourceUrl: "https://wired.com",
    date: "2026-06-14", crossLinks: [],
  },

  // ─── Digital Identity ──────────────────────────────────────────────────────
  {
    id: "did-s1", trendId: "digital-identity",
    title: "people are paying actual money for clothes that only exist online and 4 million have done it",
    summary: "Digital fashion platform DressX has passed 4M digital garment sales. Consumers are spending real money on clothes they'll only wear in photos and online. The purchase motivation is social identity, not utility.",
    source: "news", sourceName: "Vogue Business", sourceUrl: "https://voguebusiness.com",
    date: "2026-05-15", crossLinks: ["ai-s2", "arc-s1"],
  },
  {
    id: "did-s2", trendId: "digital-identity",
    title: "Balenciaga and Gucci are making real money selling outfits inside Fortnite",
    summary: "Luxury fashion's entry into gaming is deepening. Balenciaga, Gucci and Burberry have active in-game presences with millions of digital item sales. The luxury consumer is younger and more gaming-native than any previous generation.",
    source: "reddit", sourceName: "r/gaming", sourceUrl: "https://reddit.com/r/gaming",
    date: "2026-04-10", crossLinks: ["ai-s1", "spc-s1"],
  },
  {
    id: "did-s3", trendId: "digital-identity",
    title: "Stanford found that Gen Z genuinely cares about what their avatar wears as much as their real clothes",
    summary: "Research shows Gen Z treats avatar appearance with identical social weight to physical dress. Digital exclusives create the same scarcity dynamics as limited physical drops — the psychology of fashion has gone platform-agnostic.",
    source: "arxiv", sourceName: "arXiv", sourceUrl: "https://arxiv.org",
    date: "2026-03-22", crossLinks: ["ai-s5"],
  },
  {
    id: "did-s4", trendId: "digital-identity",
    title: "there's one avatar that follows you across 10,000 apps and 40 million people are already using it",
    summary: "Cross-platform avatar system Ready Player Me has 40M avatars across 10,000 apps. A universal digital self is no longer a concept — it's infrastructure. Fashion brands that ignore it are opting out of a permanent distribution channel.",
    source: "hackernews", sourceName: "Hacker News", sourceUrl: "https://news.ycombinator.com",
    date: "2026-05-30", crossLinks: ["ai-s1", "spc-s3"],
  },
  {
    id: "did-s5", trendId: "digital-identity",
    title: "fit check videos where people style their digital avatars are getting billions of views now",
    summary: "YouTube's fit-check video format — 2B+ views — has spawned a virtual variant where creators style their digital avatars and rate digital-only outfits. The format is merging physical and digital fashion culture.",
    source: "youtube", sourceName: "YouTube Trends", sourceUrl: "https://youtube.com",
    date: "2026-06-05", crossLinks: ["arc-s2"],
  },
  {
    id: "did-s6", trendId: "digital-identity",
    title: "Roblox paid $100M to fashion creators and some of them are teenagers running actual businesses",
    summary: "Roblox has paid fashion creators $100M in UGC earnings. Teen designers are running genuine fashion businesses inside games — a generation learning commerce through play. This is where the next fashion entrepreneurs are forming.",
    source: "news", sourceName: "Bloomberg", sourceUrl: "https://bloomberg.com",
    date: "2026-05-26", crossLinks: ["spc-s1"],
  },
  {
    id: "did-s7", trendId: "digital-identity",
    title: "NFT fashion is back but this time with actual perks attached instead of just hype",
    summary: "After the 2022 collapse, digital fashion NFTs are returning with utility: exclusive access, physical twins, and brand loyalty programmes attached to ownership. The speculation layer is stripped; the utility layer is real.",
    source: "reddit", sourceName: "r/web3fashion", sourceUrl: "https://reddit.com/r/web3",
    date: "2026-05-19", crossLinks: [],
  },

  // ─── AR / VR Commerce ─────────────────────────────────────────────────────
  {
    id: "arc-s1", trendId: "ar-commerce",
    title: "250 million people are using Snap's try-on thing and returns are actually down 30%",
    summary: "Snap's AR try-on has reached 250M users. Brands report 2.4x higher purchase intent and 30% lower return rates for AR-viewed products. The ROI case is no longer theoretical.",
    source: "news", sourceName: "TechCrunch", sourceUrl: "https://techcrunch.com",
    date: "2026-05-18", crossLinks: ["did-s1", "spc-s2"],
  },
  {
    id: "arc-s2", trendId: "ar-commerce",
    title: "Nike and Net-a-Porter now have fully immersive stores on Vision Pro and it's not a gimmick anymore",
    summary: "Nike, Porsche and Net-a-Porter launched spatial commerce experiences on Vision Pro. Immersive retail is becoming a serious brand channel, not an experiment. The question is no longer 'if' but 'when'.",
    source: "news", sourceName: "Dezeen", sourceUrl: "https://dezeen.com",
    date: "2026-04-22", crossLinks: ["did-s5", "spc-s1"],
  },
  {
    id: "arc-s3", trendId: "ar-commerce",
    title: "Sephora's AR makeup try-on genuinely works — 70% of people who use it end up buying",
    summary: "L'Oréal and Sephora's AR makeup try-on is reducing purchase uncertainty dramatically. 70% of users who try AR-on convert versus 40% without — a 75% relative uplift that makes the investment case unanswerable.",
    source: "news", sourceName: "Vogue Business", sourceUrl: "https://voguebusiness.com",
    date: "2026-05-02", crossLinks: ["bio-s1"],
  },
  {
    id: "arc-s4", trendId: "ar-commerce",
    title: "people are getting mad when the real product looks worse than the AR version — new problem nobody saw coming",
    summary: "r/malefashionadvice discussing 'AR try-on fatigue' — the gap between realistic AR preview and actual product is creating a new form of buyer disappointment. Higher expectations from AR are creating a new quality bar for physical product.",
    source: "reddit", sourceName: "r/malefashionadvice", sourceUrl: "https://reddit.com/r/malefashionadvice",
    date: "2026-06-08", crossLinks: [],
  },
  {
    id: "arc-s5", trendId: "ar-commerce",
    title: "nearly half of wholesale buyers would rather do a virtual showroom than go to a trade show",
    summary: "B2B fashion is adopting virtual showrooms. ORDRE and NuOrder report 40% of wholesale buyers now prefer virtual to physical showroom visits. The trade show model is being disrupted from the B2B side, not just consumer.",
    source: "news", sourceName: "WWD", sourceUrl: "https://wwd.com",
    date: "2026-05-25", crossLinks: ["spc-s2"],
  },
  {
    id: "arc-s6", trendId: "ar-commerce",
    title: "you can now find something on Pinterest, try it on virtually, and buy it all without leaving the app",
    summary: "Pinterest's AR try-on for jewellery, sunglasses, and clothing has 300M monthly users. Discovery-to-purchase in a single AR session is now possible — collapsing the traditional consideration funnel.",
    source: "news", sourceName: "TechCrunch", sourceUrl: "https://techcrunch.com",
    date: "2026-06-06", crossLinks: ["did-s5"],
  },
  {
    id: "arc-s7", trendId: "ar-commerce",
    title: "Zalando found that AR-previewed items get returned at 18% vs 38% normally — that's huge",
    summary: "Zalando's internal data shows AR-previewed items return at 18% vs 38% industry average. The ROI case for AR investment is now indisputable — it's not a UX feature, it's a margin intervention.",
    source: "news", sourceName: "Vogue Business", sourceUrl: "https://voguebusiness.com",
    date: "2026-04-20", crossLinks: [],
  },
  {
    id: "arc-s8", trendId: "ar-commerce",
    title: "the tech to virtually try on clothes is now basically a plugin any brand can just install",
    summary: "The IKEA Place model ('see it in your home') has been cloned for fashion. 50+ DTC brands now offer 'see it on your body' AR via white-label SDKs — the technology is commoditising fast.",
    source: "hackernews", sourceName: "Hacker News", sourceUrl: "https://news.ycombinator.com",
    date: "2026-05-07", crossLinks: [],
  },

  // ─── Biotech Beauty ───────────────────────────────────────────────────────
  {
    id: "bio-s1", trendId: "biotech-beauty",
    title: "L'Oréal is now testing cosmetics on lab-grown bioprinted skin instead of animals",
    summary: "L'Oréal's partnership with Poietis for bioprinted skin has replaced 30% of animal testing. EU cosmetics regulation is accelerating this shift — bioprinted skin is becoming standard testing infrastructure for the industry.",
    source: "arxiv", sourceName: "arXiv", sourceUrl: "https://arxiv.org",
    date: "2026-04-14", crossLinks: ["arc-s3", "lon-s2"],
  },
  {
    id: "bio-s2", trendId: "biotech-beauty",
    title: "skincare brands that talk about 'good bacteria' are raising millions because people finally get what it means",
    summary: "Gallinée raised $20M to scale microbiome skincare. Consumer familiarity with 'good bacteria' from gut health is directly unlocking the skin market — wellness language is migrating into beauty at speed.",
    source: "news", sourceName: "Business of Fashion", sourceUrl: "https://businessoffashion.com",
    date: "2026-05-06", crossLinks: ["lon-s1"],
  },
  {
    id: "bio-s3", trendId: "biotech-beauty",
    title: "the skincare subreddit is obsessed with fermented ingredients right now and honestly the science backs it up",
    summary: "K-beauty's fermentation techniques are going global. Fermented ingredients (galactomyces, bifida) outperform synthetics in r/SkincareAddiction community recommendations. Community consensus is now a commercial signal.",
    source: "reddit", sourceName: "r/SkincareAddiction", sourceUrl: "https://reddit.com/r/SkincareAddiction",
    date: "2026-05-29", crossLinks: [],
  },
  {
    id: "bio-s4", trendId: "biotech-beauty",
    title: "there are startups that analyse your skin microbiome and then formulate a serum specifically for you",
    summary: "Startups combine skin microbiome analysis with AI to formulate personalised serums on demand — a subscription skincare that evolves with your skin biology. The mass-customisation wave is hitting prestige beauty.",
    source: "hackernews", sourceName: "Hacker News", sourceUrl: "https://news.ycombinator.com",
    date: "2026-06-02", crossLinks: ["ai-s3"],
  },
  {
    id: "bio-s5", trendId: "biotech-beauty",
    title: "the adaptogens from your supplement shelf are now showing up in face serums",
    summary: "Adaptogens from wellness are appearing in topical formulas. The wellness-to-beauty ingredient pipeline is accelerating as consumer crossover between supplement and skincare culture deepens rapidly.",
    source: "news", sourceName: "Allure", sourceUrl: "https://allure.com",
    date: "2026-05-11", crossLinks: ["neu-s2", "lon-s3"],
  },
  {
    id: "bio-s6", trendId: "biotech-beauty",
    title: "brands are using collagen that's lab-grown through fermentation — same as bovine but no animals involved",
    summary: "Geltor and Modern Meadow produce collagen via precision fermentation — identical to bovine but animal-free. High-end brands are already formulating with it for 2027 launches, bypassing both animal farming and vegan alternatives.",
    source: "arxiv", sourceName: "arXiv", sourceUrl: "https://arxiv.org",
    date: "2026-04-01", crossLinks: ["lon-s2"],
  },
  {
    id: "bio-s7", trendId: "biotech-beauty",
    title: "exosome serums from regenerative medicine are now showing up in $400 beauty products at Sephora",
    summary: "Exosomes — cell-derived vesicles from stem cell research — are appearing in $400+ serums. Backed by clinical data, but the regulatory grey zone is narrowing. First-movers have a window before compliance requirements tighten.",
    source: "news", sourceName: "Allure", sourceUrl: "https://allure.com",
    date: "2026-05-24", crossLinks: ["lon-s2"],
  },
  {
    id: "bio-s8", trendId: "biotech-beauty",
    title: "postbiotics are the thing after probiotics and skincare reddit found out before most brands did",
    summary: "Postbiotics (metabolic byproducts of probiotics) are more stable than live cultures, with stronger clinical backing. r/SkincareAddiction is driving mainstream awareness — community channels are now an ingredient launch channel.",
    source: "reddit", sourceName: "r/SkincareAddiction", sourceUrl: "https://reddit.com/r/SkincareAddiction",
    date: "2026-06-08", crossLinks: ["bio-s3"],
  },
  {
    id: "bio-s9", trendId: "biotech-beauty",
    title: "LVMH fragrance houses are using biotech to design scent molecules that literally can't exist in nature",
    summary: "Ginkgo Bioworks uses synthetic biology to design fragrance molecules impossible to source naturally. Luxury perfumers including LVMH fragrance houses are early adopters — a new era of scientifically designed scent.",
    source: "arxiv", sourceName: "arXiv", sourceUrl: "https://arxiv.org",
    date: "2026-03-18", crossLinks: ["sus-s1"],
  },
  {
    id: "bio-s10", trendId: "biotech-beauty",
    title: "people on skincare reddit are bypassing brands entirely and buying peptides straight from research suppliers",
    summary: "r/DIYBeauty communities are cross-pollinating with biohacking — users sourcing peptides, retinoids, and growth factors directly from research suppliers. Safety concerns are rising, but it signals consumer hunger for access to professional-grade biology.",
    source: "reddit", sourceName: "r/DIYBeauty", sourceUrl: "https://reddit.com/r/DIYBeauty",
    date: "2026-05-18", crossLinks: ["neu-s4"],
  },

  // ─── Sustainable Materials ────────────────────────────────────────────────
  {
    id: "sus-s1", trendId: "sustainable-materials",
    title: "Hermès dropped a bag made from mushroom leather and it sold out in 48 hours",
    summary: "Bolt Threads' Mylo mycelium leather has been adopted by Hermès and Stella McCartney. First commercial-scale production run sold out in 48 hours — market demand is ahead of supply capacity.",
    source: "news", sourceName: "Dezeen", sourceUrl: "https://dezeen.com",
    date: "2026-04-05", crossLinks: ["3dp-s3"],
  },
  {
    id: "sus-s2", trendId: "sustainable-materials",
    title: "there are fashion brands dyeing clothes with algae now and it's actually carbon negative",
    summary: "Algaeing secured three fashion group partnerships to replace synthetic dyes and fibres with algae-based alternatives. Production is carbon-negative — a materials system that removes more carbon than it emits.",
    source: "news", sourceName: "Fast Company", sourceUrl: "https://fastcompany.com",
    date: "2026-05-17", crossLinks: ["3dp-s2"],
  },
  {
    id: "sus-s3", trendId: "sustainable-materials",
    title: "people are calling out 'recycled' labels and demanding actual lifecycle data — greenwashing doesn't fly anymore",
    summary: "r/SustainableFashion shows increasing consumer sophistication — demanding lifecycle analysis (LCA) data, not just 'recycled' labels. Community consensus is an early indicator of regulatory direction: the EU is listening.",
    source: "reddit", sourceName: "r/SustainableFashion", sourceUrl: "https://reddit.com/r/SustainableFashion",
    date: "2026-06-03", crossLinks: [],
  },
  {
    id: "sus-s4", trendId: "sustainable-materials",
    title: "someone figured out how to make plastic from captured greenhouse gas and it's entering fashion production",
    summary: "Newlight Technologies' AirCarbon, made from captured greenhouse gas, is entering fashion production. Dell and IKEA already use it at scale. Fashion brands are now piloting — the material is proven and the supply chain exists.",
    source: "arxiv", sourceName: "arXiv", sourceUrl: "https://arxiv.org",
    date: "2026-04-30", crossLinks: ["3dp-s1"],
  },
  {
    id: "sus-s5", trendId: "sustainable-materials",
    title: "a YouTube channel about sustainable materials has 2 million subscribers which says everything",
    summary: "Channels explaining biomaterials and sustainable chemistry are exploding. Material Matters has 2M subscribers — signalling consumer hunger for materials literacy that brands should be meeting, not ignoring.",
    source: "youtube", sourceName: "YouTube", sourceUrl: "https://youtube.com",
    date: "2026-05-24", crossLinks: [],
  },
  {
    id: "sus-s6", trendId: "sustainable-materials",
    title: "Nike released shoes made from pineapple leaves as mainline and the first 100,000 sold out immediately",
    summary: "Ananas Anam's Piñatex has moved from niche to Nike mainline. First 100K unit run sold out within days — consumer demand for credible bio-materials is outpacing brands' willingness to supply them.",
    source: "news", sourceName: "Fast Company", sourceUrl: "https://fastcompany.com",
    date: "2026-05-05", crossLinks: [],
  },
  {
    id: "sus-s7", trendId: "sustainable-materials",
    title: "Gucci and Valentino are doing mainline pieces in ocean-plastic nylon and it genuinely looks good",
    summary: "Econyl's regenerated nylon from ocean plastic has moved into Gucci and Valentino mainline collections. The contradiction between 'premium' and 'sustainable' is collapsing — it's now a design advantage, not a compromise.",
    source: "news", sourceName: "Dezeen", sourceUrl: "https://dezeen.com",
    date: "2026-04-26", crossLinks: ["sus-s3"],
  },
  {
    id: "sus-s8", trendId: "sustainable-materials",
    title: "Adidas is testing a dyeing process that uses 50x less water and is carbon negative — this is actually huge",
    summary: "Colorifix's biological dyeing process uses 50x less water and is carbon-negative. Post-Series B with Adidas and M&S as active pilots — the dyeing industry is on the verge of a biological disruption.",
    source: "news", sourceName: "Business of Fashion", sourceUrl: "https://businessoffashion.com",
    date: "2026-06-03", crossLinks: [],
  },
  {
    id: "sus-s9", trendId: "sustainable-materials",
    title: "the EU is making brands trace every material by 2027 and most of them have no idea how to do that yet",
    summary: "EU Digital Product Passport regulation mandates material traceability for all fashion sold in Europe from 2027. Most brands cannot answer basic DPP questions about their own supply chains — the compliance gap is significant and closing fast.",
    source: "news", sourceName: "WWD", sourceUrl: "https://wwd.com",
    date: "2026-05-28", crossLinks: ["sus-s3", "sus-s4"],
  },

  // ─── 3D Printing ──────────────────────────────────────────────────────────
  {
    id: "3dp-s1", trendId: "3d-printing",
    title: "there's a company printing fully recyclable shoes in 45 minutes and New Balance is already testing it",
    summary: "Zellerfeld is 3D-printing fully recyclable shoes in 45 minutes per pair. ASICS and New Balance are in pilot programmes. The traditional factory-to-shelf model is being challenged at its manufacturing core.",
    source: "news", sourceName: "Wired", sourceUrl: "https://wired.com",
    date: "2026-04-18", crossLinks: ["sus-s4"],
  },
  {
    id: "3dp-s2", trendId: "3d-printing",
    title: "3D printers can now do soft and hard materials in one go which basically solves why 3D clothes always felt wrong",
    summary: "New multi-material FDM printers combine rigid and flexible filaments in one print — solving the wearability problem that blocked fashion 3D printing for a decade. The technical barrier has fallen.",
    source: "arxiv", sourceName: "arXiv", sourceUrl: "https://arxiv.org",
    date: "2026-05-03", crossLinks: ["sus-s2"],
  },
  {
    id: "3dp-s3", trendId: "3d-printing",
    title: "Iris van Herpen's entire collection was 3D printed and eight museums bought pieces from it",
    summary: "Van Herpen's AW26 collection was 100% 3D printed. Acquired by 8 major museums. 3D printing has crossed from novelty to legitimate couture — with institutional validation that will accelerate industry adoption.",
    source: "news", sourceName: "Dezeen", sourceUrl: "https://dezeen.com",
    date: "2026-03-30", crossLinks: ["sus-s1"],
  },
  {
    id: "3dp-s4", trendId: "3d-printing",
    title: "people are designing and 3D printing their own accessories at home and there's a whole community around it",
    summary: "r/3Dprinting and r/fashiondesign crossover communities are growing rapidly. Consumers designing and printing their own accessories at home represent a new form of fashion production — and a new form of fashion consumer.",
    source: "reddit", sourceName: "r/3Dprinting", sourceUrl: "https://reddit.com/r/3Dprinting",
    date: "2026-05-28", crossLinks: [],
  },
  {
    id: "3dp-s5", trendId: "3d-printing",
    title: "you can get a lip applicator literally shaped to your lips specifically which is a bit much but also kind of amazing",
    summary: "Niche brands are offering custom 3D-printed makeup applicators shaped to individual lip and face profiles. The market is small, but it signals a personalisation-at-manufacturing-level wave that will hit every product category.",
    source: "news", sourceName: "Allure", sourceUrl: "https://allure.com",
    date: "2026-06-07", crossLinks: ["bio-s4"],
  },

  // ─── Wearables ────────────────────────────────────────────────────────────
  {
    id: "wear-s1", trendId: "wearables",
    title: "the Oura ring sold 2 million units — health rings are just accessories now, not fitness gadgets",
    summary: "Oura Ring Gen 4 sold 2M units in 2025. Health rings are mainstream accessories — the question is no longer whether consumers will wear health tech, but whether fashion brands will design it before tech companies own the aesthetic.",
    source: "news", sourceName: "TechCrunch", sourceUrl: "https://techcrunch.com",
    date: "2026-04-08", crossLinks: ["lon-s1", "neu-s1"],
  },
  {
    id: "wear-s2", trendId: "wearables",
    title: "Google and Levi's made a denim jacket that tracks your health and you literally can't tell it's smart",
    summary: "Jacquard by Google's latest iteration integrates gesture control and health sensing into standard denim weaves. The tech is invisible — just denim. This is the template for how smart fabrics should enter fashion.",
    source: "news", sourceName: "Wired", sourceUrl: "https://wired.com",
    date: "2026-05-14", crossLinks: ["neu-s3"],
  },
  {
    id: "wear-s3", trendId: "wearables",
    title: "people are wearing their CGM patches openly like an accessory and brands are starting to make covers for them",
    summary: "CGM patches (Abbott Libre, Dexcom) are being worn openly as health signals. Fashion brands are exploring decorative patch covers — a new category emerging from medical devices into fashion accessories.",
    source: "reddit", sourceName: "r/diabetes_t1", sourceUrl: "https://reddit.com/r/diabetes_t1",
    date: "2026-06-04", crossLinks: ["lon-s2"],
  },
  {
    id: "wear-s4", trendId: "wearables",
    title: "YouTube creators are doing styling hauls with their Oura and Whoop like they're fashion pieces not gadgets",
    summary: "Health wearable unboxings and reviews are merging with fashion haul culture on YouTube. Creators are styling Oura, Whoop, and patches as accessories. The category has crossed from gadget to fashion accessory in cultural framing.",
    source: "youtube", sourceName: "YouTube", sourceUrl: "https://youtube.com",
    date: "2026-05-31", crossLinks: [],
  },
  {
    id: "wear-s5", trendId: "wearables",
    title: "Tag Heuer is putting health sensors inside luxury jewellery and watches and it actually looks like jewellery",
    summary: "Tag Heuer, Movado, and emerging jewellery brands are partnering with sensor companies to embed health monitoring in luxury jewellery. A new premium category is forming at the intersection of health data and jewellery.",
    source: "news", sourceName: "Bloomberg", sourceUrl: "https://bloomberg.com",
    date: "2026-05-09", crossLinks: ["lon-s1"],
  },
  {
    id: "wear-s6", trendId: "wearables",
    title: "the reason Ray-Ban Meta is actually selling is because it looks like normal sunglasses not a tech device",
    summary: "Ray-Ban Meta's success is less about AI features and more about looking like sunglasses. The lesson for fashion brands is unambiguous: wearable tech must be fashion first, always. Tech companies know this now — the window to compete is closing.",
    source: "news", sourceName: "Wired", sourceUrl: "https://wired.com",
    date: "2026-04-15", crossLinks: ["did-s1"],
  },
  {
    id: "wear-s7", trendId: "wearables",
    title: "suncare brands are making UV patches that people are treating like skin accessories",
    summary: "UV monitoring skin patches are becoming fashion accessories. Branded patch covers from suncare companies signal a new wearable-beauty product category forming at the intersection of health, skincare, and fashion.",
    source: "news", sourceName: "Allure", sourceUrl: "https://allure.com",
    date: "2026-05-20", crossLinks: ["bio-s7"],
  },
  {
    id: "wear-s8", trendId: "wearables",
    title: "femtech wearables are growing faster than anything else in health tech and fashion brands are barely paying attention",
    summary: "Menstrual cycle health tracking wearables (Emmaline, Tempdrop) are growing 200% YoY. Femtech is the fastest growing wearable category and largely ignored by fashion — a significant white space with a clear consumer.",
    source: "news", sourceName: "TechCrunch", sourceUrl: "https://techcrunch.com",
    date: "2026-06-01", crossLinks: ["lon-s3"],
  },
  {
    id: "wear-s9", trendId: "wearables",
    title: "a $3k sleep pod is showing up in fashion editorials now — sleep optimisation is the new status flex",
    summary: "Eight Sleep's Pod Pro at $3K+ is appearing in fashion editorials. Sleep optimisation devices are becoming lifestyle status symbols — sleep tech is following the same arc from medical device to luxury accessory that fitness trackers took.",
    source: "youtube", sourceName: "YouTube", sourceUrl: "https://youtube.com",
    date: "2026-05-13", crossLinks: ["lon-s2"],
  },
  {
    id: "wear-s10", trendId: "wearables",
    title: "LVMH is sewing NFC chips into clothes so you can scan the tag to verify it's real and register it to yourself",
    summary: "LVMH and Kering are embedding NFC chips in stitching for provenance verification and new-owner loyalty registration. The authentication chip is becoming a relationship channel — every sale triggers a brand interaction.",
    source: "hackernews", sourceName: "Hacker News", sourceUrl: "https://news.ycombinator.com",
    date: "2026-04-28", crossLinks: ["did-s7"],
  },
  {
    id: "wear-s11", trendId: "wearables",
    title: "people who wear health tech say they'd give up 20% of features if it just looked better — huge opening for fashion",
    summary: "r/wearables community survey shows users would sacrifice 20% of features for better aesthetics. The data that doesn't get worn is worthless — fashion brands have a structural aesthetic advantage over tech companies if they move now.",
    source: "reddit", sourceName: "r/wearables", sourceUrl: "https://reddit.com/r/wearables",
    date: "2026-06-12", crossLinks: [],
  },

  // ─── Neurotech ────────────────────────────────────────────────────────────
  {
    id: "neu-s1", trendId: "neurotech",
    title: "there's a meditation headband that reads your brain activity and half a million people use it regularly",
    summary: "Muse's EEG headband has 500K active users. Meditation and stress measurement is becoming data-driven — opening neurocosmetics and stress-responsive product categories that don't yet have a mainstream brand leader.",
    source: "news", sourceName: "MIT Technology Review", sourceUrl: "https://technologyreview.com",
    date: "2026-04-25", crossLinks: ["wear-s1", "lon-s3"],
  },
  {
    id: "neu-s2", trendId: "neurotech",
    title: "some brands are making skincare that specifically targets your nervous system and it's called neurocosmetics now",
    summary: "Brands are formulating products that target the nervous system — adaptogens, ashwagandha, and EEG-validated ingredients for 'skin stress response' as a clinical category. Neurocosmetics is naming what wellness skincare has been building toward.",
    source: "arxiv", sourceName: "arXiv", sourceUrl: "https://arxiv.org",
    date: "2026-05-19", crossLinks: ["bio-s5"],
  },
  {
    id: "neu-s3", trendId: "neurotech",
    title: "Neuralink can now send signals to AND from the brain in humans which is still wild to say out loud",
    summary: "Neuralink's human trials show bidirectional reading/writing capability. Consumer applications are 5+ years away but the cultural conversation is now. Brands that understand the implications early will set the category agenda when it arrives.",
    source: "news", sourceName: "Wired", sourceUrl: "https://wired.com",
    date: "2026-03-15", crossLinks: ["wear-s2"],
  },
  {
    id: "neu-s4", trendId: "neurotech",
    title: "the nootropics community invented the phrase 'skin stack' and now normal skincare people are using it",
    summary: "Cognitive enhancement community discussions (r/nootropics) are bleeding into skincare — 'skin stack' terminology borrowed from supplement culture is entering mainstream beauty vocabulary. Communities are naming a category that brands haven't yet.",
    source: "reddit", sourceName: "r/nootropics", sourceUrl: "https://reddit.com/r/nootropics",
    date: "2026-05-27", crossLinks: ["bio-s5"],
  },
  {
    id: "neu-s5", trendId: "neurotech",
    title: "Calm has 150 million people doing daily brain wellness routines — there's a massive untapped product gap there",
    summary: "Calm (150M users) and Headspace are normalising daily neurowellness routines. Brands that connect to these existing daily rituals have a powerful behaviour anchor for product integration — the ritual is already there, the product is not.",
    source: "news", sourceName: "Fast Company", sourceUrl: "https://fastcompany.com",
    date: "2026-04-19", crossLinks: ["lon-s3"],
  },

  // ─── Spatial Computing ────────────────────────────────────────────────────
  {
    id: "spc-s1", trendId: "spatial-computing",
    title: "Vision Pro hit 2 million units and brands building experiences now will own the format when it goes mass market",
    summary: "Vision Pro hit 2M units in 18 months — slower than iPhone but faster than iPad. The spatial app ecosystem is growing. Fashion brands building experiences now accumulate first-mover brand recall before the device reaches mass market.",
    source: "news", sourceName: "Bloomberg", sourceUrl: "https://bloomberg.com",
    date: "2026-05-21", crossLinks: ["did-s2", "arc-s2"],
  },
  {
    id: "spc-s2", trendId: "spatial-computing",
    title: "Net-a-Porter's Vision Pro boutique converts at 3x their regular app which is honestly staggering",
    summary: "Net-a-Porter's Vision Pro app lets users browse a life-size virtual boutique. Conversion rate is 3x their standard app — physical scale and immersion are proving to be decisive commercial advantages in spatial commerce.",
    source: "news", sourceName: "Vogue Business", sourceUrl: "https://voguebusiness.com",
    date: "2026-05-16", crossLinks: ["arc-s1", "arc-s5"],
  },
  {
    id: "spc-s3", trendId: "spatial-computing",
    title: "there's now a version of you that follows you across every app and game — digital identity is becoming infrastructure",
    summary: "Open Metaverse ID and Ready Player Me are enabling a persistent digital self. Your digital identity follows you across games, apps, and workplaces — fashion becomes the expression layer of a permanent digital identity.",
    source: "hackernews", sourceName: "Hacker News", sourceUrl: "https://news.ycombinator.com",
    date: "2026-06-01", crossLinks: ["did-s4"],
  },
  {
    id: "spc-s4", trendId: "spatial-computing",
    title: "spatial designer is becoming a job title — visionOS tutorials on YouTube are up 400% this year",
    summary: "A new creator category is emerging: spatial experience designers. YouTube tutorials on visionOS development are up 400% YoY — the talent pool for spatial brand experiences is forming, and the brands that engage it now will pay lower rates.",
    source: "youtube", sourceName: "YouTube", sourceUrl: "https://youtube.com",
    date: "2026-05-27", crossLinks: [],
  },
  {
    id: "spc-s5", trendId: "spatial-computing",
    title: "half the people who bought Vision Pro returned it — the other half are building their entire workflow around it",
    summary: "r/VisionPro shows a split community: power users building productive spatial workflows vs mainstream users returning devices. The use case gap is real — brand experiences that solve a genuine need, not just demonstrate novelty, will retain users.",
    source: "reddit", sourceName: "r/VisionPro", sourceUrl: "https://reddit.com/r/VisionPro",
    date: "2026-06-09", crossLinks: [],
  },
  {
    id: "spc-s6", trendId: "spatial-computing",
    title: "Samsung just dropped an XR headset for $999 so now fashion brands have to design for two spatial platforms at once",
    summary: "Samsung's Android XR headset at $999 opens spatial computing to a broader audience. Fashion brands must now design for two competing spatial platforms simultaneously — doubling the creative and technical investment required.",
    source: "news", sourceName: "TechCrunch", sourceUrl: "https://techcrunch.com",
    date: "2026-05-29", crossLinks: ["arc-s2"],
  },
  {
    id: "spc-s7", trendId: "spatial-computing",
    title: "Valentino hosted a fashion show in Decentraland and 2 million people virtually attended",
    summary: "Decentraland's 2026 Fashion Week drew 2M virtual attendees. Valentino and Diesel hosted spatial shows. The format is maturing from gimmick to genuine brand channel with meaningful reach numbers.",
    source: "news", sourceName: "Vogue Business", sourceUrl: "https://voguebusiness.com",
    date: "2026-03-25", crossLinks: ["did-s2", "spc-s1"],
  },
  {
    id: "spc-s8", trendId: "spatial-computing",
    title: "people are rewatching fashion shows in Vision Pro with spatial audio and it apparently feels like front row",
    summary: "Spatial audio is being layered onto fashion show recordings for Vision Pro — creating immersive front-row experiences available to anyone with a headset, anywhere, at any time. The fashion show is becoming a spatial media format.",
    source: "youtube", sourceName: "YouTube", sourceUrl: "https://youtube.com",
    date: "2026-04-30", crossLinks: [],
  },

  // ─── Longevity ────────────────────────────────────────────────────────────
  {
    id: "lon-s1", trendId: "longevity",
    title: "Bryan Johnson spends $2M a year trying not to age and now every supplement brand is copying his protocol",
    summary: "Bryan Johnson's $2M/year longevity protocol has spawned a mass-market version. Supplement brands, beauty lines, and wearable companies are all 'longevity' branding now — the concept has successfully crossed from extreme biohacking to mainstream consumer aspiration.",
    source: "news", sourceName: "Wired", sourceUrl: "https://wired.com",
    date: "2026-04-12", crossLinks: ["bio-s2", "wear-s1", "wear-s5"],
  },
  {
    id: "lon-s2", trendId: "longevity",
    title: "there are anti-ageing compounds with actual peer-reviewed research behind them showing up in high-end skincare",
    summary: "Senolytic compounds (quercetin, fisetin) are entering premium skincare — backed by peer-reviewed research, not just marketing language. A new functional anti-ageing category is forming where clinical evidence is the minimum entry requirement.",
    source: "arxiv", sourceName: "arXiv", sourceUrl: "https://arxiv.org",
    date: "2026-05-04", crossLinks: ["bio-s1", "wear-s3"],
  },
  {
    id: "lon-s3", trendId: "longevity",
    title: "longevity clinics with NAD+ drips and epigenetic testing are opening everywhere like a new kind of luxury spa",
    summary: "Longevity clinics offering NAD+ drips, epigenetic testing, and personalised protocols are opening in every major city. A $10B industry by 2028 — a new luxury health category sitting directly adjacent to fashion's premium consumer.",
    source: "news", sourceName: "Bloomberg", sourceUrl: "https://bloomberg.com",
    date: "2026-05-22", crossLinks: ["bio-s5", "neu-s1", "neu-s5"],
  },
  {
    id: "lon-s4", trendId: "longevity",
    title: "there's a 400,000 person reddit community that knows more about longevity science than most brand R&D teams",
    summary: "r/longevity has 400K members discussing supplements, protocols, and research. This is consumer-driven longevity science — highly demanding, deeply literate, and deeply skeptical of marketing claims. Authenticity and clinical evidence are table stakes here.",
    source: "reddit", sourceName: "r/longevity", sourceUrl: "https://reddit.com/r/longevity",
    date: "2026-06-06", crossLinks: [],
  },
  {
    id: "lon-s5", trendId: "longevity",
    title: "longevity podcasters now get more views on YouTube than fitness influencers — it's the new wellness",
    summary: "Andrew Huberman, Peter Attia, and Rhonda Patrick have collectively surpassed traditional fitness creators in views. Longevity content is the new wellness genre — and its audience buys with higher income and more intentionally than the fitness audience.",
    source: "youtube", sourceName: "YouTube", sourceUrl: "https://youtube.com",
    date: "2026-05-13", crossLinks: [],
  },
  {
    id: "lon-s6", trendId: "longevity",
    title: "people are taking a transplant rejection drug to slow ageing and prescriptions are up 400% at longevity clinics",
    summary: "Off-label rapamycin prescriptions for longevity are up 400% in US longevity clinics. A drug developed for transplant rejection is becoming a lifestyle supplement for the upper-middle class — the medicalisation of longevity is accelerating.",
    source: "arxiv", sourceName: "arXiv", sourceUrl: "https://arxiv.org",
    date: "2026-04-07", crossLinks: ["lon-s3"],
  },
  {
    id: "lon-s7", trendId: "longevity",
    title: "you can test your biological age for $200 now and people are tracking it like a fitness stat",
    summary: "TruDiagnostic, Elysium, and similar biological age tests are now available DTC for $200. Consumers are tracking biological vs chronological age — a new performance metric that creates a clear hook for wellness and beauty brands.",
    source: "news", sourceName: "Bloomberg", sourceUrl: "https://bloomberg.com",
    date: "2026-05-01", crossLinks: ["wear-s1"],
  },
  {
    id: "lon-s8", trendId: "longevity",
    title: "500,000 cold plunge tubs have sold — it went from biohacker thing to normal suburban backyard in like two years",
    summary: "Plunge and Polar Monkeys have sold 500K cold plunge tubs. From biohacker niche to suburban backyard staple in 18 months. Recovery culture is the new fitness culture — and it's reshaping how consumers think about health products.",
    source: "youtube", sourceName: "YouTube", sourceUrl: "https://youtube.com",
    date: "2026-05-19", crossLinks: ["neu-s1"],
  },
  {
    id: "lon-s9", trendId: "longevity",
    title: "people are posting their VO2 max score on Instagram the same way they used to post their new bag",
    summary: "VO2 max scores are being shared on social media as health status signals. Apple Watch is adding VO2 max to watch faces. Fitness data is the new luxury flex — brands that can connect to this performance identity have a powerful positioning anchor.",
    source: "reddit", sourceName: "r/longevity", sourceUrl: "https://reddit.com/r/longevity",
    date: "2026-06-08", crossLinks: ["wear-s4"],
  },
  {
    id: "lon-s10", trendId: "longevity",
    title: "collagen supplements are the fastest growing beauty category — eating your skincare is apparently a real thing now",
    summary: "Beauty-from-within collagen supplements are the fastest-growing beauty category. Vital Proteins (now Nestlé) signals that food is the new skincare — and the market will be $8B by 2027. The boundary between nutrition and beauty is dissolving.",
    source: "news", sourceName: "Business of Fashion", sourceUrl: "https://businessoffashion.com",
    date: "2026-04-23", crossLinks: ["bio-s6"],
  },
  {
    id: "lon-s11", trendId: "longevity",
    title: "NAD+ drip bars are opening next to concept stores in Milan and NYC like it's the most normal thing",
    summary: "IV therapy and NAD+ drip bars are opening next to concept stores in fashion capitals. Luxury wellness experiences are becoming part of fashion retail neighbourhoods — a new kind of experiential retail adjacency forming.",
    source: "news", sourceName: "Vogue", sourceUrl: "https://vogue.com",
    date: "2026-05-08", crossLinks: ["lon-s3"],
  },
  {
    id: "lon-s12", trendId: "longevity",
    title: "everyone is trying to find the next retinol and it's basically a race with a decade of market share at stake",
    summary: "Bakuchiol, HPR, and retinaldehyde are competing to replace retinol. The skincare industry is in active ingredient upheaval — whoever wins the replacement race gets a decade of market share and reference position in millions of routines.",
    source: "news", sourceName: "Allure", sourceUrl: "https://allure.com",
    date: "2026-06-05", crossLinks: ["bio-s7"],
  },
  {
    id: "lon-s13", trendId: "longevity",
    title: "watching videos of 100-year-olds living their daily life is getting 300 million views a month and honestly it makes sense",
    summary: "Content following the daily routines of 100+ year-olds hits 300M views/month. Okinawan diet, Sardinian movement patterns, and Seventh-Day Adventist habits are now mainstream consumer topics — longevity is a cultural movement, not a health category.",
    source: "youtube", sourceName: "YouTube", sourceUrl: "https://youtube.com",
    date: "2026-06-01", crossLinks: [],
  },
];

export function computeLayout(): {
  trends: (Trend & { radius: number })[];
  signalPositions: Map<string, { x: number; y: number }>;
} {
  const MIN_RADIUS = 55;
  const MAX_RADIUS = 110;
  const ORBIT_PADDING = 200;
  const SIGNAL_W = 190;
  const SIGNAL_H = 64;

  const signalPositions = new Map<string, { x: number; y: number }>();
  const trends = TRENDS.map((t) => {
    const radius = MIN_RADIUS + (t.relevanceScore / 100) * (MAX_RADIUS - MIN_RADIUS);
    const signals = SIGNALS.filter((s) => s.trendId === t.id);
    const orbitRadius = radius + ORBIT_PADDING;
    signals.forEach((sig, i) => {
      const angle = (2 * Math.PI * i) / signals.length - Math.PI / 2;
      const x = t.position.x + orbitRadius * Math.cos(angle) - SIGNAL_W / 2;
      const y = t.position.y + orbitRadius * Math.sin(angle) - SIGNAL_H / 2;
      signalPositions.set(sig.id, { x, y });
    });
    return { ...t, radius };
  });

  return { trends, signalPositions };
}

export function getSourceIcon(source: Signal["source"]): string {
  return {
    reddit: "🔴",
    news: "📰",
    youtube: "▶️",
    arxiv: "🔬",
    hackernews: "🟠",
    manual: "✦",
  }[source ?? "manual"] ?? "✦";
}
