import { Trend, Signal } from "@/types";

export const TRENDS: Trend[] = [
  {
    id: "ai-creativity",
    name: "The Machine That Replaced Your Moodboard",
    description: "AI isn't a tool anymore — it's a creative collaborator that designs faster, cheaper, and stranger than any human team. Fashion is only beginning to reckon with what that means.",
    color: "#FF2D78",
    relevanceScore: 88,
    redditQuery: "AI fashion design generative",
    newsQuery: "AI generative fashion design",
    position: { x: 520, y: 380 },
    whyRelevant: "AI is compressing creative cycles by 10x. Brands that don't integrate AI into design, forecasting, and campaigns will be out-produced by those that do. The competitive advantage is structural, not marginal — it compounds every quarter.",
    trajectory: "Over the next 18 months, AI moves from creative augmentation to creative autonomy. The debate shifts from 'should we use AI' to 'who owns the output' and 'how do we maintain brand authenticity'. Brands that build proprietary AI training sets from their own archives will command a meaningful moat. Expect the first major AI-only fashion label to debut by 2027.",
    nextSteps: [
      "Audit which creative workflows can be AI-augmented this quarter and run a 30-day pilot",
      "Test one AI-generated campaign concept with a controlled consumer group and measure recall vs. traditional creative",
      "Draft an AI ethics policy covering synthetic models, attribution, and data provenance before regulation forces your hand",
    ],
  },
  {
    id: "digital-identity",
    name: "Dressing the Self You Are Online",
    description: "Your avatar's outfit matters as much as what you wore to dinner. Digital fashion, virtual personas, and online self-expression are becoming billion-dollar identity markets.",
    color: "#FFE600",
    relevanceScore: 82,
    redditQuery: "digital identity avatar virtual fashion",
    newsQuery: "digital identity virtual avatar fashion",
    position: { x: 1100, y: 220 },
    whyRelevant: "The next generation measures social status as much by digital appearance as physical. Brands that only exist physically are invisible to the demographic most likely to drive culture for the next 20 years. Digital drops carry zero inventory risk.",
    trajectory: "Digital identity consolidates around 2–3 cross-platform standards (Ready Player Me, Open Metaverse ID) making digital wardrobes persistent across gaming, work, and social. Fashion's digital revenue goes from experimental to budget line by 2027. The first luxury house to offer a full digital twin wardrobe with every physical purchase will own the format.",
    nextSteps: [
      "Map your brand's current presence (or absence) across Roblox, Fortnite, and Ready Player Me",
      "Commission one digital-only drop to test virtual commerce mechanics without physical production risk",
      "Study how gaming fashion economics differ from physical — scarcity, resale, and community dynamics all work differently",
    ],
  },
  {
    id: "ar-commerce",
    name: "Try Before You Never Buy",
    description: "AR try-on is collapsing the distance between desire and purchase. Virtual fitting rooms are cutting returns, lifting conversion, and making physical retail look slow.",
    color: "#7B2FFF",
    relevanceScore: 79,
    redditQuery: "AR VR shopping try-on retail",
    newsQuery: "augmented reality virtual try-on shopping",
    position: { x: 1700, y: 380 },
    whyRelevant: "AR try-on is already delivering measurable ROI — 30–50% lower returns, 2–3x higher conversion. It's no longer experimental. Brands without it are at a structural conversion disadvantage, especially as mobile AR becomes the default browsing behaviour.",
    trajectory: "AR try-on becomes table stakes for e-commerce within 24 months — similar to how product photography was once optional. The next phase is social AR: outfit try-on directly in Instagram and TikTok stories before purchase. Brands that build AR asset libraries now will be significantly ahead when the platforms mandate it.",
    nextSteps: [
      "Integrate AR try-on SDK into product pages for your top 20 SKUs and track return rates before/after",
      "Brief your wholesale buyers on virtual showroom capabilities — 40% already prefer virtual to physical visits",
      "Test AR-first product reveals in campaign launches to measure pre-purchase engagement",
    ],
  },
  {
    id: "biotech-beauty",
    name: "The Lab Is the New Beauty Counter",
    description: "Bioprinted skin. Microbiome formulas. Fermentation actives. The beauty industry is becoming a biotech industry — and the brands that understand biology will win.",
    color: "#00FF87",
    relevanceScore: 71,
    redditQuery: "biotech skincare microbiome beauty science",
    newsQuery: "biotech beauty skincare innovation",
    position: { x: 280, y: 900 },
    whyRelevant: "Consumer sophistication about ingredients is accelerating faster than most brands' R&D cycles. The brands that own efficacy narratives backed by biology command 3–5x premium pricing. Biotech is now table stakes for prestige positioning.",
    trajectory: "Biotech beauty splits into two tracks: mass-market microbiome (already arriving) and ultra-premium regenerative ingredients (exosomes, lab-grown collagen). By 2028, a biologically credentialed product range — with peer-reviewed data — becomes the minimum requirement for prestige positioning. Brands without clinical evidence will compete only on price.",
    nextSteps: [
      "Audit your ingredient portfolio against microbiome, postbiotic, and exosome pipelines — identify one to pilot in the next NPD cycle",
      "Commission an independent clinical study on a hero ingredient; peer-reviewed data is the new minimum for prestige credibility",
      "Map the regulatory status of your most innovative ingredients in key markets (EU, US, South Korea)",
    ],
  },
  {
    id: "sustainable-materials",
    name: "Fashion Made From Air and Fungus",
    description: "Mycelium leather. Algae fibre. Carbon-captured nylon. A generation of radical materials is replacing conventional inputs — and making sustainability a design advantage, not a compromise.",
    color: "#FF6B35",
    relevanceScore: 74,
    redditQuery: "sustainable fashion materials mycelium algae",
    newsQuery: "sustainable bio-materials fashion innovation",
    position: { x: 900, y: 980 },
    whyRelevant: "EU Digital Product Passport regulation makes material traceability mandatory for all fashion sold in Europe from 2027. Brands caught greenwashing face fines up to €4M. The sustainable materials story must become supply-chain fact, not marketing copy.",
    trajectory: "The EU DPP deadline forces a materials reckoning in 2026–27. Brands that have already piloted alternative materials will pivot to scale; late movers will pay premium prices for constrained bio-material supply. Mycelium, algae, and carbon-captured fibres transition from niche to premium mainstream. The brands that own their material story own the premium consumer.",
    nextSteps: [
      "Begin lifecycle analysis (LCA) for your top 5 materials before DPP compliance becomes mandatory in 2027",
      "Pilot one alternative material in a limited collection to test consumer response and supply chain viability",
      "Audit your supplier tier 2 and tier 3 data — most brands can't answer basic DPP questions about their own supply chains",
    ],
  },
  {
    id: "3d-printing",
    name: "The Printer That Ate the Factory",
    description: "Zero inventory. No waste. Shoes in 45 minutes. 3D printing is rewriting the rules of fashion manufacturing — and the brands piloting it now are building an insurmountable lead.",
    color: "#00D4FF",
    relevanceScore: 61,
    redditQuery: "3D printing fashion footwear manufacturing",
    newsQuery: "3D printing fashion manufacturing",
    position: { x: 1500, y: 960 },
    whyRelevant: "3D printing solves fashion's two most expensive problems: overstock and speed-to-market. Early movers building IP in printable design accumulate a manufacturing and creative lead that compounds. The technology window for first-mover advantage is 18–36 months.",
    trajectory: "3D printing moves from couture novelty to accessories mainstream within 3 years. Footwear is the beachhead — Zellerfeld and New Balance are proving it works at scale. The next category is jewellery, then eyewear. On-demand local printing eliminates the global shipping model for small-batch products. Consumer-facing home printing for accessories becomes real by 2028.",
    nextSteps: [
      "Identify one product category (accessories, footwear, eyewear) for a 3D printing pilot and commission a cost comparison",
      "Explore IP ownership structure for your digital design files — this is the new product archive",
      "Connect with Zellerfeld, Stratasys, or EOS for a design collaboration conversation",
    ],
  },
  {
    id: "wearables",
    name: "Your Body Is Now a Dashboard",
    description: "Rings, patches, and smart fabrics are turning health data into a continuous stream. The question isn't whether consumers will wear health tech — it's whether fashion brands will design it.",
    color: "#0066FF",
    relevanceScore: 67,
    redditQuery: "smart wearables health ring fitness tracker",
    newsQuery: "smart wearables health monitoring",
    position: { x: 1950, y: 820 },
    whyRelevant: "Health data is becoming a lifestyle accessory. Fashion brands that design beautiful wearable hardware will own a category that tech companies cannot win on aesthetics alone. The market is open and the consumer demand signal is unambiguous.",
    trajectory: "The wearables market bifurcates: tech-led (Apple, Samsung, Google) competing on capability, and fashion-led competing on aesthetics and identity. Fashion's window to enter the category before tech brands solve the aesthetics problem is closing — 2–3 years at most. Smart fabrics democratise health sensing beyond devices and into everyday garments by 2028.",
    nextSteps: [
      "Commission consumer research: would your customer wear a health-tracking piece from your brand, and at what price point?",
      "Identify 2–3 health sensor companies for a co-design conversation on embedding sensors in existing product lines",
      "Study the Ray-Ban Meta case study — the lesson is 'fashion-first, tech-second' and it's directly applicable",
    ],
  },
  {
    id: "neurotech",
    name: "Skincare for Your Nervous System",
    description: "Adaptogens in your serum. EEG-validated ingredients. Brain-computer interfaces on the horizon. Neurotechnology is quietly redefining what beauty and wellness products are supposed to do.",
    color: "#FF00C1",
    relevanceScore: 48,
    redditQuery: "neurotech BCI brain computer interface wellness",
    newsQuery: "neurotech consumer brain computer interface",
    position: { x: 460, y: 1480 },
    whyRelevant: "Neurotech is 3–7 years from consumer mainstream, but the brands that build literacy now will set the category agenda. Neurocosmetics, stress-responsive products, and biofeedback beauty are all nascent but growing at 40%+ annually.",
    trajectory: "Neurotech moves from wellness niche to beauty category within 5 years. The path: adaptogen-infused topicals now → EEG-validated stress-response formulas by 2027 → wearable-integrated skincare by 2029. The first brand to credibly combine biometric feedback with a skincare product will own a premium category for a decade.",
    nextSteps: [
      "Brief your R&D team on neurocosmetics ingredients (ashwagandha, l-theanine, lion's mane) and their regulatory status",
      "Monitor Neuralink and consumer BCI timelines quarterly — build an internal briefing document now",
      "Map the overlap between your customer's wellness routines and stress management — this is the entry point",
    ],
  },
  {
    id: "spatial-computing",
    name: "Shopping in a World That Doesn't Exist Yet",
    description: "Spatial commerce isn't the metaverse hype cycle — it's the quiet infrastructure being built right now inside Vision Pro apps and virtual showrooms. First-movers will own the format.",
    color: "#C8FF00",
    relevanceScore: 58,
    redditQuery: "spatial computing Apple Vision Pro metaverse",
    newsQuery: "spatial computing Apple Vision Pro brands",
    position: { x: 1100, y: 1500 },
    whyRelevant: "Spatial commerce is the next retail format. Brands establishing presence in Vision Pro and Galaxy XR now will own brand recall when devices reach mass market. Net-a-Porter is already reporting 3x conversion vs. its standard app in spatial.",
    trajectory: "Spatial computing reaches the mass market tipping point in 2026–27 as Samsung Galaxy XR drives Android adoption and Vision Pro Gen 2 drops to sub-$2K. Fashion becomes the anchor category for spatial retail — the 'try-on room' killer app that justifies headset ownership. Brands with spatial presence in 2025 will have a 2–3 year head start on those that wait.",
    nextSteps: [
      "Greenlight a Vision Pro brand experience — even a minimal one — within the next 6 months",
      "Assign one person to monitor spatial platform developments and circulate a monthly briefing",
      "Brief your 3D/design team on the additional requirements for spatial content vs. standard e-commerce assets",
    ],
  },
  {
    id: "longevity",
    name: "The Business of Never Getting Old",
    description: "Longevity isn't a niche biohacking obsession anymore — it's a mainstream cultural obsession with a $600B market attached. Every beauty, wellness, and lifestyle brand needs a position on it.",
    color: "#FF3333",
    relevanceScore: 73,
    redditQuery: "longevity anti-aging biohacking health",
    newsQuery: "longevity anti-ageing culture wellness",
    position: { x: 1750, y: 1460 },
    whyRelevant: "Longevity has moved from biohacker niche to mainstream with 400K-strong Reddit communities and Andrew Huberman at 8M YouTube subscribers. Every beauty, wellness, and lifestyle brand now competes in the longevity space whether they know it or not.",
    trajectory: "Longevity becomes the defining consumer category of the late 2020s — bigger than 'wellness' was in the 2010s. The convergence of biological age testing, GLP-1 body recomposition, and longevity clinics creates a new premium health consumer with significant disposable income. Beauty brands that don't reframe around longevity by 2026 will find their anti-ageing positioning feels anachronistic.",
    nextSteps: [
      "Reframe your brand's core product benefits through a longevity lens — 'protection', 'restoration', and 'biological age' are the new positioning vocabulary",
      "Commission consumer research on how your customer thinks about ageing, health optimisation, and biological vs. chronological age",
      "Identify one longevity clinic group or community for a strategic partnership — these are the new luxury wellness channels",
    ],
  },
];

export const SIGNALS: Signal[] = [
  // ─── AI & Generative Creativity ───────────────────────────────────────────
  {
    id: "ai-s1", trendId: "ai-creativity",
    title: "AI is cutting luxury mood board creation from weeks to hours",
    summary: "Major fashion houses are using Midjourney and Adobe Firefly to generate seasonal mood boards and concept visuals, compressing 3-week creative processes into hours.",
    source: "news", sourceName: "Business of Fashion", sourceUrl: "https://businessoffashion.com",
    date: "2026-05-12", crossLinks: ["did-s2", "did-s4"],
  },
  {
    id: "ai-s2", trendId: "ai-creativity",
    title: "H&M and Levi's are running AI-generated model campaigns — without photoshoots",
    summary: "H&M and Levi's are deploying AI-generated models to diversify campaign imagery without photoshoots. Raises major questions around transparency and authenticity that neither brand has fully addressed.",
    source: "news", sourceName: "Vogue Business", sourceUrl: "https://voguebusiness.com",
    date: "2026-04-28", crossLinks: ["did-s1"],
  },
  {
    id: "ai-s3", trendId: "ai-creativity",
    title: "AI can produce a production-ready tech pack from a creative brief alone",
    summary: "Cala's AI takes a concept brief and outputs production-ready tech packs. Early adopters report 60% faster development cycles — the product development pipeline is being fundamentally compressed.",
    source: "hackernews", sourceName: "Hacker News", sourceUrl: "https://news.ycombinator.com",
    date: "2026-05-20", crossLinks: [],
  },
  {
    id: "ai-s4", trendId: "ai-creativity",
    title: "Junior designers fear AI is coming for their entry-level roles",
    summary: "r/femalefashionadvice and r/malefashionadvice show growing anxiety among junior designers about AI replacing entry-level creative roles. The fear is specific and widely shared — this is an industry labour signal.",
    source: "reddit", sourceName: "r/femalefashionadvice", sourceUrl: "https://reddit.com/r/femalefashionadvice",
    date: "2026-06-01", crossLinks: [],
  },
  {
    id: "ai-s5", trendId: "ai-creativity",
    title: "AI forecasting tools are predicting microtrends 6 months out — threatening WGSN",
    summary: "Heuritech and Trendalytics use computer vision on social media to predict microtrends 6 months out. The traditional forecasting agency model — expensive, slow, human — is under structural threat.",
    source: "news", sourceName: "WWD", sourceUrl: "https://wwd.com",
    date: "2026-05-08", crossLinks: ["did-s3"],
  },
  {
    id: "ai-s6", trendId: "ai-creativity",
    title: "Vogue published a fashion film that was entirely AI-generated",
    summary: "OpenAI's Sora is being used by independent directors to produce fashion short films at near-zero budget. A Vogue-published film was entirely AI-generated — the format has crossed into editorial legitimacy.",
    source: "news", sourceName: "Vogue", sourceUrl: "https://vogue.com",
    date: "2026-05-30", crossLinks: [],
  },
  {
    id: "ai-s7", trendId: "ai-creativity",
    title: "AI is generating hundreds of textile colourways in hours, not weeks",
    summary: "Fashion studios are using Adobe Firefly's vector generation to produce print patterns and colourways in bulk. What took weeks of manual artwork now takes an afternoon — the design team's role is shifting from maker to curator.",
    source: "hackernews", sourceName: "Hacker News", sourceUrl: "https://news.ycombinator.com",
    date: "2026-06-09", crossLinks: ["ai-s3"],
  },
  {
    id: "ai-s8", trendId: "ai-creativity",
    title: "200 independent designers are suing AI companies for training on their work without consent",
    summary: "A coalition of 200 independent fashion designers filed a class action suit against Stability AI. This is the landmark IP case that will define AI's relationship with creative ownership — every brand using AI creative tools has a stake in the outcome.",
    source: "news", sourceName: "The Guardian", sourceUrl: "https://theguardian.com",
    date: "2026-06-11", crossLinks: [],
  },
  {
    id: "ai-s9", trendId: "ai-creativity",
    title: "AI virtual sampling is cutting colourway development costs by 70%",
    summary: "Brands using AI to generate and approve colourways virtually before physical sampling report 70% cost savings. Physical strike-offs are becoming the exception — a structural shift in how fashion products are developed.",
    source: "news", sourceName: "Business of Fashion", sourceUrl: "https://businessoffashion.com",
    date: "2026-05-03", crossLinks: ["sus-s3"],
  },
  {
    id: "ai-s10", trendId: "ai-creativity",
    title: "Fashion school students at Parsons and CSM are submitting AI-generated portfolios",
    summary: "Gen Z designers are AI-native from day one. Students at Parsons and CSM are submitting AI-generated portfolios. Educators are split on whether to embrace or ban. The generation has already decided.",
    source: "reddit", sourceName: "r/fashiondesign", sourceUrl: "https://reddit.com/r/fashiondesign",
    date: "2026-06-13", crossLinks: ["ai-s4"],
  },
  {
    id: "ai-s11", trendId: "ai-creativity",
    title: "AI is auto-generating construction notes and BOMs from 3D garment files",
    summary: "CLO 3D's AI assistant auto-generates construction notes, BOM, and tolerances from a 3D garment. The technical designer role is being fundamentally redefined from execution to oversight.",
    source: "hackernews", sourceName: "Hacker News", sourceUrl: "https://news.ycombinator.com",
    date: "2026-04-17", crossLinks: [],
  },
  {
    id: "ai-s12", trendId: "ai-creativity",
    title: "AI-only fashion accounts with no human creators are hitting 10M followers",
    summary: "AI-only fashion accounts (@AIRunway, @NeuralCouture) generate daily AI looks and are outperforming human creator accounts in engagement. The influencer category has a new entrant — one with zero overhead.",
    source: "reddit", sourceName: "r/artificial", sourceUrl: "https://reddit.com/r/artificial",
    date: "2026-06-02", crossLinks: ["did-s5"],
  },
  {
    id: "ai-s13", trendId: "ai-creativity",
    title: "Midjourney v7's fabric realism is triggering returns on AI-generated product imagery",
    summary: "Midjourney v7's fabric simulation is photorealistic enough to fool buyers. First reports of returns triggered by AI-generated product imagery are appearing — a new liability category for e-commerce brands.",
    source: "news", sourceName: "Wired", sourceUrl: "https://wired.com",
    date: "2026-06-14", crossLinks: [],
  },

  // ─── Digital Identity ──────────────────────────────────────────────────────
  {
    id: "did-s1", trendId: "digital-identity",
    title: "DressX has sold 4M digital garments — consumers pay real money for digital-only clothes",
    summary: "Digital fashion platform DressX has passed 4M digital garment sales. Consumers are spending real money on clothes they'll only wear in photos and online. The purchase motivation is social identity, not utility.",
    source: "news", sourceName: "Vogue Business", sourceUrl: "https://voguebusiness.com",
    date: "2026-05-15", crossLinks: ["ai-s2", "arc-s1"],
  },
  {
    id: "did-s2", trendId: "digital-identity",
    title: "Balenciaga, Gucci, and Burberry are selling millions of items inside Fortnite",
    summary: "Luxury fashion's entry into gaming is deepening. Balenciaga, Gucci and Burberry have active in-game presences with millions of digital item sales. The luxury consumer is younger and more gaming-native than any previous generation.",
    source: "reddit", sourceName: "r/gaming", sourceUrl: "https://reddit.com/r/gaming",
    date: "2026-04-10", crossLinks: ["ai-s1", "spc-s1"],
  },
  {
    id: "did-s3", trendId: "digital-identity",
    title: "Stanford research confirms Gen Z treats avatar appearance with the same social weight as physical dress",
    summary: "Research shows Gen Z treats avatar appearance with identical social weight to physical dress. Digital exclusives create the same scarcity dynamics as limited physical drops — the psychology of fashion has gone platform-agnostic.",
    source: "arxiv", sourceName: "arXiv", sourceUrl: "https://arxiv.org",
    date: "2026-03-22", crossLinks: ["ai-s5"],
  },
  {
    id: "did-s4", trendId: "digital-identity",
    title: "Ready Player Me serves 40M avatars across 10,000 apps — a universal digital self is becoming infrastructure",
    summary: "Cross-platform avatar system Ready Player Me has 40M avatars across 10,000 apps. A universal digital self is no longer a concept — it's infrastructure. Fashion brands that ignore it are opting out of a permanent distribution channel.",
    source: "hackernews", sourceName: "Hacker News", sourceUrl: "https://news.ycombinator.com",
    date: "2026-05-30", crossLinks: ["ai-s1", "spc-s3"],
  },
  {
    id: "did-s5", trendId: "digital-identity",
    title: "YouTube's fit-check format has spawned a virtual variant with billions of views",
    summary: "YouTube's fit-check video format — 2B+ views — has spawned a virtual variant where creators style their digital avatars and rate digital-only outfits. The format is merging physical and digital fashion culture.",
    source: "youtube", sourceName: "YouTube Trends", sourceUrl: "https://youtube.com",
    date: "2026-06-05", crossLinks: ["arc-s2"],
  },
  {
    id: "did-s6", trendId: "digital-identity",
    title: "Roblox has paid fashion creators $100M — teen designers are running real businesses in-game",
    summary: "Roblox has paid fashion creators $100M in UGC earnings. Teen designers are running genuine fashion businesses inside games — a generation learning commerce through play. This is where the next fashion entrepreneurs are forming.",
    source: "news", sourceName: "Bloomberg", sourceUrl: "https://bloomberg.com",
    date: "2026-05-26", crossLinks: ["spc-s1"],
  },
  {
    id: "did-s7", trendId: "digital-identity",
    title: "Digital fashion NFTs are returning — this time with utility hooks instead of speculation",
    summary: "After the 2022 collapse, digital fashion NFTs are returning with utility: exclusive access, physical twins, and brand loyalty programmes attached to ownership. The speculation layer is stripped; the utility layer is real.",
    source: "reddit", sourceName: "r/web3fashion", sourceUrl: "https://reddit.com/r/web3",
    date: "2026-05-19", crossLinks: [],
  },

  // ─── AR / VR Commerce ─────────────────────────────────────────────────────
  {
    id: "arc-s1", trendId: "ar-commerce",
    title: "Snap's AR try-on reaches 250M users with 2.4x purchase intent and 30% fewer returns",
    summary: "Snap's AR try-on has reached 250M users. Brands report 2.4x higher purchase intent and 30% lower return rates for AR-viewed products. The ROI case is no longer theoretical.",
    source: "news", sourceName: "TechCrunch", sourceUrl: "https://techcrunch.com",
    date: "2026-05-18", crossLinks: ["did-s1", "spc-s2"],
  },
  {
    id: "arc-s2", trendId: "ar-commerce",
    title: "Nike and Net-a-Porter have launched spatial commerce on Vision Pro — immersive retail is real",
    summary: "Nike, Porsche and Net-a-Porter launched spatial commerce experiences on Vision Pro. Immersive retail is becoming a serious brand channel, not an experiment. The question is no longer 'if' but 'when'.",
    source: "news", sourceName: "Dezeen", sourceUrl: "https://dezeen.com",
    date: "2026-04-22", crossLinks: ["did-s5", "spc-s1"],
  },
  {
    id: "arc-s3", trendId: "ar-commerce",
    title: "L'Oréal and Sephora's AR try-on converts 70% of users vs 40% without it",
    summary: "L'Oréal and Sephora's AR makeup try-on is reducing purchase uncertainty dramatically. 70% of users who try AR-on convert versus 40% without — a 75% relative uplift that makes the investment case unanswerable.",
    source: "news", sourceName: "Vogue Business", sourceUrl: "https://voguebusiness.com",
    date: "2026-05-02", crossLinks: ["bio-s1"],
  },
  {
    id: "arc-s4", trendId: "ar-commerce",
    title: "AR try-on fatigue is emerging — the gap between preview and product is a new kind of disappointment",
    summary: "r/malefashionadvice discussing 'AR try-on fatigue' — the gap between realistic AR preview and actual product is creating a new form of buyer disappointment. Higher expectations from AR are creating a new quality bar for physical product.",
    source: "reddit", sourceName: "r/malefashionadvice", sourceUrl: "https://reddit.com/r/malefashionadvice",
    date: "2026-06-08", crossLinks: [],
  },
  {
    id: "arc-s5", trendId: "ar-commerce",
    title: "40% of wholesale buyers now prefer virtual showrooms to physical trade show visits",
    summary: "B2B fashion is adopting virtual showrooms. ORDRE and NuOrder report 40% of wholesale buyers now prefer virtual to physical showroom visits. The trade show model is being disrupted from the B2B side, not just consumer.",
    source: "news", sourceName: "WWD", sourceUrl: "https://wwd.com",
    date: "2026-05-25", crossLinks: ["spc-s2"],
  },
  {
    id: "arc-s6", trendId: "ar-commerce",
    title: "Pinterest AR try-on reaches 300M users — discovery-to-purchase in a single session",
    summary: "Pinterest's AR try-on for jewellery, sunglasses, and clothing has 300M monthly users. Discovery-to-purchase in a single AR session is now possible — collapsing the traditional consideration funnel.",
    source: "news", sourceName: "TechCrunch", sourceUrl: "https://techcrunch.com",
    date: "2026-06-06", crossLinks: ["did-s5"],
  },
  {
    id: "arc-s7", trendId: "ar-commerce",
    title: "Zalando data: AR-previewed items return at 18% vs the 38% industry average",
    summary: "Zalando's internal data shows AR-previewed items return at 18% vs 38% industry average. The ROI case for AR investment is now indisputable — it's not a UX feature, it's a margin intervention.",
    source: "news", sourceName: "Vogue Business", sourceUrl: "https://voguebusiness.com",
    date: "2026-04-20", crossLinks: [],
  },
  {
    id: "arc-s8", trendId: "ar-commerce",
    title: "50+ DTC fashion brands have deployed 'see it on your body' AR via white-label SDK",
    summary: "The IKEA Place model ('see it in your home') has been cloned for fashion. 50+ DTC brands now offer 'see it on your body' AR via white-label SDKs — the technology is commoditising fast.",
    source: "hackernews", sourceName: "Hacker News", sourceUrl: "https://news.ycombinator.com",
    date: "2026-05-07", crossLinks: [],
  },

  // ─── Biotech Beauty ───────────────────────────────────────────────────────
  {
    id: "bio-s1", trendId: "biotech-beauty",
    title: "L'Oréal's bioprinted skin has replaced 30% of animal testing for cosmetics",
    summary: "L'Oréal's partnership with Poietis for bioprinted skin has replaced 30% of animal testing. EU cosmetics regulation is accelerating this shift — bioprinted skin is becoming standard testing infrastructure for the industry.",
    source: "arxiv", sourceName: "arXiv", sourceUrl: "https://arxiv.org",
    date: "2026-04-14", crossLinks: ["arc-s3", "lon-s2"],
  },
  {
    id: "bio-s2", trendId: "biotech-beauty",
    title: "Microbiome brand Gallinée raised $20M as consumer 'good bacteria' literacy unlocks skincare",
    summary: "Gallinée raised $20M to scale microbiome skincare. Consumer familiarity with 'good bacteria' from gut health is directly unlocking the skin market — wellness language is migrating into beauty at speed.",
    source: "news", sourceName: "Business of Fashion", sourceUrl: "https://businessoffashion.com",
    date: "2026-05-06", crossLinks: ["lon-s1"],
  },
  {
    id: "bio-s3", trendId: "biotech-beauty",
    title: "Fermented actives are overtaking synthetics in skincare community recommendations",
    summary: "K-beauty's fermentation techniques are going global. Fermented ingredients (galactomyces, bifida) outperform synthetics in r/SkincareAddiction community recommendations. Community consensus is now a commercial signal.",
    source: "reddit", sourceName: "r/SkincareAddiction", sourceUrl: "https://reddit.com/r/SkincareAddiction",
    date: "2026-05-29", crossLinks: [],
  },
  {
    id: "bio-s4", trendId: "biotech-beauty",
    title: "Startups are combining microbiome analysis with AI to create personalised serums on demand",
    summary: "Startups combine skin microbiome analysis with AI to formulate personalised serums on demand — a subscription skincare that evolves with your skin biology. The mass-customisation wave is hitting prestige beauty.",
    source: "hackernews", sourceName: "Hacker News", sourceUrl: "https://news.ycombinator.com",
    date: "2026-06-02", crossLinks: ["ai-s3"],
  },
  {
    id: "bio-s5", trendId: "biotech-beauty",
    title: "Ashwagandha, reishi, and lion's mane are appearing in topical skincare formulas",
    summary: "Adaptogens from wellness are appearing in topical formulas. The wellness-to-beauty ingredient pipeline is accelerating as consumer crossover between supplement and skincare culture deepens rapidly.",
    source: "news", sourceName: "Allure", sourceUrl: "https://allure.com",
    date: "2026-05-11", crossLinks: ["neu-s2", "lon-s3"],
  },
  {
    id: "bio-s6", trendId: "biotech-beauty",
    title: "Lab-grown collagen via fermentation is animal-free — prestige brands are formulating with it",
    summary: "Geltor and Modern Meadow produce collagen via precision fermentation — identical to bovine but animal-free. High-end brands are already formulating with it for 2027 launches, bypassing both animal farming and vegan alternatives.",
    source: "arxiv", sourceName: "arXiv", sourceUrl: "https://arxiv.org",
    date: "2026-04-01", crossLinks: ["lon-s2"],
  },
  {
    id: "bio-s7", trendId: "biotech-beauty",
    title: "Exosome serums from regenerative medicine are crossing into $400+ consumer beauty",
    summary: "Exosomes — cell-derived vesicles from stem cell research — are appearing in $400+ serums. Backed by clinical data, but the regulatory grey zone is narrowing. First-movers have a window before compliance requirements tighten.",
    source: "news", sourceName: "Allure", sourceUrl: "https://allure.com",
    date: "2026-05-24", crossLinks: ["lon-s2"],
  },
  {
    id: "bio-s8", trendId: "biotech-beauty",
    title: "Postbiotics — fermentation byproducts — are the emerging hero ingredient after probiotics",
    summary: "Postbiotics (metabolic byproducts of probiotics) are more stable than live cultures, with stronger clinical backing. r/SkincareAddiction is driving mainstream awareness — community channels are now an ingredient launch channel.",
    source: "reddit", sourceName: "r/SkincareAddiction", sourceUrl: "https://reddit.com/r/SkincareAddiction",
    date: "2026-06-08", crossLinks: ["bio-s3"],
  },
  {
    id: "bio-s9", trendId: "biotech-beauty",
    title: "Ginkgo Bioworks is designing novel fragrance molecules using CRISPR — luxury perfumers are first adopters",
    summary: "Ginkgo Bioworks uses synthetic biology to design fragrance molecules impossible to source naturally. Luxury perfumers including LVMH fragrance houses are early adopters — a new era of scientifically designed scent.",
    source: "arxiv", sourceName: "arXiv", sourceUrl: "https://arxiv.org",
    date: "2026-03-18", crossLinks: ["sus-s1"],
  },
  {
    id: "bio-s10", trendId: "biotech-beauty",
    title: "DIY skincare communities are sourcing peptides and growth factors directly from research suppliers",
    summary: "r/DIYBeauty communities are cross-pollinating with biohacking — users sourcing peptides, retinoids, and growth factors directly from research suppliers. Safety concerns are rising, but it signals consumer hunger for access to professional-grade biology.",
    source: "reddit", sourceName: "r/DIYBeauty", sourceUrl: "https://reddit.com/r/DIYBeauty",
    date: "2026-05-18", crossLinks: ["neu-s4"],
  },

  // ─── Sustainable Materials ────────────────────────────────────────────────
  {
    id: "sus-s1", trendId: "sustainable-materials",
    title: "Hermès and Stella McCartney have adopted mycelium leather — first run sold out in 48 hours",
    summary: "Bolt Threads' Mylo mycelium leather has been adopted by Hermès and Stella McCartney. First commercial-scale production run sold out in 48 hours — market demand is ahead of supply capacity.",
    source: "news", sourceName: "Dezeen", sourceUrl: "https://dezeen.com",
    date: "2026-04-05", crossLinks: ["3dp-s3"],
  },
  {
    id: "sus-s2", trendId: "sustainable-materials",
    title: "Algaeing has partnered with three fashion groups to replace synthetic dyes with carbon-negative algae",
    summary: "Algaeing secured three fashion group partnerships to replace synthetic dyes and fibres with algae-based alternatives. Production is carbon-negative — a materials system that removes more carbon than it emits.",
    source: "news", sourceName: "Fast Company", sourceUrl: "https://fastcompany.com",
    date: "2026-05-17", crossLinks: ["3dp-s2"],
  },
  {
    id: "sus-s3", trendId: "sustainable-materials",
    title: "Consumers are demanding lifecycle analysis data, not recycled labels — greenwashing fatigue is real",
    summary: "r/SustainableFashion shows increasing consumer sophistication — demanding lifecycle analysis (LCA) data, not just 'recycled' labels. Community consensus is an early indicator of regulatory direction: the EU is listening.",
    source: "reddit", sourceName: "r/SustainableFashion", sourceUrl: "https://reddit.com/r/SustainableFashion",
    date: "2026-06-03", crossLinks: [],
  },
  {
    id: "sus-s4", trendId: "sustainable-materials",
    title: "AirCarbon — plastic made from captured greenhouse gas — is entering fashion production",
    summary: "Newlight Technologies' AirCarbon, made from captured greenhouse gas, is entering fashion production. Dell and IKEA already use it at scale. Fashion brands are now piloting — the material is proven and the supply chain exists.",
    source: "arxiv", sourceName: "arXiv", sourceUrl: "https://arxiv.org",
    date: "2026-04-30", crossLinks: ["3dp-s1"],
  },
  {
    id: "sus-s5", trendId: "sustainable-materials",
    title: "Materials science creators like 'Material Matters' are hitting 2M subscribers on YouTube",
    summary: "Channels explaining biomaterials and sustainable chemistry are exploding. Material Matters has 2M subscribers — signalling consumer hunger for materials literacy that brands should be meeting, not ignoring.",
    source: "youtube", sourceName: "YouTube", sourceUrl: "https://youtube.com",
    date: "2026-05-24", crossLinks: [],
  },
  {
    id: "sus-s6", trendId: "sustainable-materials",
    title: "Nike has moved Piñatex pineapple-leaf leather into mainline — first 100K units sold out immediately",
    summary: "Ananas Anam's Piñatex has moved from niche to Nike mainline. First 100K unit run sold out within days — consumer demand for credible bio-materials is outpacing brands' willingness to supply them.",
    source: "news", sourceName: "Fast Company", sourceUrl: "https://fastcompany.com",
    date: "2026-05-05", crossLinks: [],
  },
  {
    id: "sus-s7", trendId: "sustainable-materials",
    title: "Econyl ocean-plastic nylon is now in Gucci and Valentino mainline — premium sustainability is losing its contradiction",
    summary: "Econyl's regenerated nylon from ocean plastic has moved into Gucci and Valentino mainline collections. The contradiction between 'premium' and 'sustainable' is collapsing — it's now a design advantage, not a compromise.",
    source: "news", sourceName: "Dezeen", sourceUrl: "https://dezeen.com",
    date: "2026-04-26", crossLinks: ["sus-s3"],
  },
  {
    id: "sus-s8", trendId: "sustainable-materials",
    title: "Colorifix raised $30M for biological dyeing that uses 50x less water and is carbon-negative",
    summary: "Colorifix's biological dyeing process uses 50x less water and is carbon-negative. Post-Series B with Adidas and M&S as active pilots — the dyeing industry is on the verge of a biological disruption.",
    source: "news", sourceName: "Business of Fashion", sourceUrl: "https://businessoffashion.com",
    date: "2026-06-03", crossLinks: [],
  },
  {
    id: "sus-s9", trendId: "sustainable-materials",
    title: "EU law mandates full material traceability for all fashion sold in Europe from 2027 — most brands can't comply yet",
    summary: "EU Digital Product Passport regulation mandates material traceability for all fashion sold in Europe from 2027. Most brands cannot answer basic DPP questions about their own supply chains — the compliance gap is significant and closing fast.",
    source: "news", sourceName: "WWD", sourceUrl: "https://wwd.com",
    date: "2026-05-28", crossLinks: ["sus-s3", "sus-s4"],
  },

  // ─── 3D Printing ──────────────────────────────────────────────────────────
  {
    id: "3dp-s1", trendId: "3d-printing",
    title: "Zellerfeld is 3D-printing fully recyclable shoes in 45 minutes — ASICS and New Balance are piloting",
    summary: "Zellerfeld is 3D-printing fully recyclable shoes in 45 minutes per pair. ASICS and New Balance are in pilot programmes. The traditional factory-to-shelf model is being challenged at its manufacturing core.",
    source: "news", sourceName: "Wired", sourceUrl: "https://wired.com",
    date: "2026-04-18", crossLinks: ["sus-s4"],
  },
  {
    id: "3dp-s2", trendId: "3d-printing",
    title: "Multi-material 3D printing solves fashion's wearability problem in a single print",
    summary: "New multi-material FDM printers combine rigid and flexible filaments in one print — solving the wearability problem that blocked fashion 3D printing for a decade. The technical barrier has fallen.",
    source: "arxiv", sourceName: "arXiv", sourceUrl: "https://arxiv.org",
    date: "2026-05-03", crossLinks: ["sus-s2"],
  },
  {
    id: "3dp-s3", trendId: "3d-printing",
    title: "Iris van Herpen's AW26 collection was 100% 3D-printed — acquired by 8 major museums",
    summary: "Van Herpen's AW26 collection was 100% 3D printed. Acquired by 8 major museums. 3D printing has crossed from novelty to legitimate couture — with institutional validation that will accelerate industry adoption.",
    source: "news", sourceName: "Dezeen", sourceUrl: "https://dezeen.com",
    date: "2026-03-30", crossLinks: ["sus-s1"],
  },
  {
    id: "3dp-s4", trendId: "3d-printing",
    title: "DIY fashion printing communities are exploding — consumers are designing and printing their own accessories at home",
    summary: "r/3Dprinting and r/fashiondesign crossover communities are growing rapidly. Consumers designing and printing their own accessories at home represent a new form of fashion production — and a new form of fashion consumer.",
    source: "reddit", sourceName: "r/3Dprinting", sourceUrl: "https://reddit.com/r/3Dprinting",
    date: "2026-05-28", crossLinks: [],
  },
  {
    id: "3dp-s5", trendId: "3d-printing",
    title: "Custom 3D-printed makeup applicators shaped to individual face profiles signal a personalisation wave",
    summary: "Niche brands are offering custom 3D-printed makeup applicators shaped to individual lip and face profiles. The market is small, but it signals a personalisation-at-manufacturing-level wave that will hit every product category.",
    source: "news", sourceName: "Allure", sourceUrl: "https://allure.com",
    date: "2026-06-07", crossLinks: ["bio-s4"],
  },

  // ─── Wearables ────────────────────────────────────────────────────────────
  {
    id: "wear-s1", trendId: "wearables",
    title: "Oura Ring Gen 4 has sold 2M units — health rings are now mainstream accessories",
    summary: "Oura Ring Gen 4 sold 2M units in 2025. Health rings are mainstream accessories — the question is no longer whether consumers will wear health tech, but whether fashion brands will design it before tech companies own the aesthetic.",
    source: "news", sourceName: "TechCrunch", sourceUrl: "https://techcrunch.com",
    date: "2026-04-08", crossLinks: ["lon-s1", "neu-s1"],
  },
  {
    id: "wear-s2", trendId: "wearables",
    title: "Google and Levi's Jacquard integrates gesture control and health sensing invisibly into denim",
    summary: "Jacquard by Google's latest iteration integrates gesture control and health sensing into standard denim weaves. The tech is invisible — just denim. This is the template for how smart fabrics should enter fashion.",
    source: "news", sourceName: "Wired", sourceUrl: "https://wired.com",
    date: "2026-05-14", crossLinks: ["neu-s3"],
  },
  {
    id: "wear-s3", trendId: "wearables",
    title: "Continuous glucose monitors are being worn openly as health status signals — a new accessories category is forming",
    summary: "CGM patches (Abbott Libre, Dexcom) are being worn openly as health signals. Fashion brands are exploring decorative patch covers — a new category emerging from medical devices into fashion accessories.",
    source: "reddit", sourceName: "r/diabetes_t1", sourceUrl: "https://reddit.com/r/diabetes_t1",
    date: "2026-06-04", crossLinks: ["lon-s2"],
  },
  {
    id: "wear-s4", trendId: "wearables",
    title: "Wearable hauls are replacing tech reviews on YouTube — Oura and Whoop are being styled, not spec'd",
    summary: "Health wearable unboxings and reviews are merging with fashion haul culture on YouTube. Creators are styling Oura, Whoop, and patches as accessories. The category has crossed from gadget to fashion accessory in cultural framing.",
    source: "youtube", sourceName: "YouTube", sourceUrl: "https://youtube.com",
    date: "2026-05-31", crossLinks: [],
  },
  {
    id: "wear-s5", trendId: "wearables",
    title: "Tag Heuer and Movado are embedding health monitoring in luxury jewellery — a new price-point category opens",
    summary: "Tag Heuer, Movado, and emerging jewellery brands are partnering with sensor companies to embed health monitoring in luxury jewellery. A new premium category is forming at the intersection of health data and jewellery.",
    source: "news", sourceName: "Bloomberg", sourceUrl: "https://bloomberg.com",
    date: "2026-05-09", crossLinks: ["lon-s1"],
  },
  {
    id: "wear-s6", trendId: "wearables",
    title: "Ray-Ban Meta's success is about aesthetics, not AI — fashion-first is the lesson for the whole category",
    summary: "Ray-Ban Meta's success is less about AI features and more about looking like sunglasses. The lesson for fashion brands is unambiguous: wearable tech must be fashion first, always. Tech companies know this now — the window to compete is closing.",
    source: "news", sourceName: "Wired", sourceUrl: "https://wired.com",
    date: "2026-04-15", crossLinks: ["did-s1"],
  },
  {
    id: "wear-s7", trendId: "wearables",
    title: "Neutrogena and L'Oréal are racing to own the UV-tracking patch market as fashion accessory",
    summary: "UV monitoring skin patches are becoming fashion accessories. Branded patch covers from suncare companies signal a new wearable-beauty product category forming at the intersection of health, skincare, and fashion.",
    source: "news", sourceName: "Allure", sourceUrl: "https://allure.com",
    date: "2026-05-20", crossLinks: ["bio-s7"],
  },
  {
    id: "wear-s8", trendId: "wearables",
    title: "Femtech wearables are growing 200% YoY — the fastest category in health tech, largely ignored by fashion",
    summary: "Menstrual cycle health tracking wearables (Emmaline, Tempdrop) are growing 200% YoY. Femtech is the fastest growing wearable category and largely ignored by fashion — a significant white space with a clear consumer.",
    source: "news", sourceName: "TechCrunch", sourceUrl: "https://techcrunch.com",
    date: "2026-06-01", crossLinks: ["lon-s3"],
  },
  {
    id: "wear-s9", trendId: "wearables",
    title: "Eight Sleep's $3K sleep pod is crossing from bedroom to fashion editorial — sleep tech is the new luxury status",
    summary: "Eight Sleep's Pod Pro at $3K+ is appearing in fashion editorials. Sleep optimisation devices are becoming lifestyle status symbols — sleep tech is following the same arc from medical device to luxury accessory that fitness trackers took.",
    source: "youtube", sourceName: "YouTube", sourceUrl: "https://youtube.com",
    date: "2026-05-13", crossLinks: ["lon-s2"],
  },
  {
    id: "wear-s10", trendId: "wearables",
    title: "LVMH and Kering are embedding NFC authentication chips in garment stitching for provenance and loyalty",
    summary: "LVMH and Kering are embedding NFC chips in stitching for provenance verification and new-owner loyalty registration. The authentication chip is becoming a relationship channel — every sale triggers a brand interaction.",
    source: "hackernews", sourceName: "Hacker News", sourceUrl: "https://news.ycombinator.com",
    date: "2026-04-28", crossLinks: ["did-s7"],
  },
  {
    id: "wear-s11", trendId: "wearables",
    title: "Wearable users say they'd sacrifice 20% of features for better design — fashion brands have a structural advantage",
    summary: "r/wearables community survey shows users would sacrifice 20% of features for better aesthetics. The data that doesn't get worn is worthless — fashion brands have a structural aesthetic advantage over tech companies if they move now.",
    source: "reddit", sourceName: "r/wearables", sourceUrl: "https://reddit.com/r/wearables",
    date: "2026-06-12", crossLinks: [],
  },

  // ─── Neurotech ────────────────────────────────────────────────────────────
  {
    id: "neu-s1", trendId: "neurotech",
    title: "Muse's EEG meditation headband has 500K active users — stress measurement is becoming data-driven",
    summary: "Muse's EEG headband has 500K active users. Meditation and stress measurement is becoming data-driven — opening neurocosmetics and stress-responsive product categories that don't yet have a mainstream brand leader.",
    source: "news", sourceName: "MIT Technology Review", sourceUrl: "https://technologyreview.com",
    date: "2026-04-25", crossLinks: ["wear-s1", "lon-s3"],
  },
  {
    id: "neu-s2", trendId: "neurotech",
    title: "Brands are formulating skincare products that target the nervous system — a new category called neurocosmetics",
    summary: "Brands are formulating products that target the nervous system — adaptogens, ashwagandha, and EEG-validated ingredients for 'skin stress response' as a clinical category. Neurocosmetics is naming what wellness skincare has been building toward.",
    source: "arxiv", sourceName: "arXiv", sourceUrl: "https://arxiv.org",
    date: "2026-05-19", crossLinks: ["bio-s5"],
  },
  {
    id: "neu-s3", trendId: "neurotech",
    title: "Neuralink has confirmed bidirectional brain-signal capability in humans — consumer applications are 5+ years away",
    summary: "Neuralink's human trials show bidirectional reading/writing capability. Consumer applications are 5+ years away but the cultural conversation is now. Brands that understand the implications early will set the category agenda when it arrives.",
    source: "news", sourceName: "Wired", sourceUrl: "https://wired.com",
    date: "2026-03-15", crossLinks: ["wear-s2"],
  },
  {
    id: "neu-s4", trendId: "neurotech",
    title: "'Skin stack' terminology is emerging from nootropic communities into mainstream skincare vocabulary",
    summary: "Cognitive enhancement community discussions (r/nootropics) are bleeding into skincare — 'skin stack' terminology borrowed from supplement culture is entering mainstream beauty vocabulary. Communities are naming a category that brands haven't yet.",
    source: "reddit", sourceName: "r/nootropics", sourceUrl: "https://reddit.com/r/nootropics",
    date: "2026-05-27", crossLinks: ["bio-s5"],
  },
  {
    id: "neu-s5", trendId: "neurotech",
    title: "Calm's 150M users are normalising daily neurowellness rituals — an entry point for brand integration",
    summary: "Calm (150M users) and Headspace are normalising daily neurowellness routines. Brands that connect to these existing daily rituals have a powerful behaviour anchor for product integration — the ritual is already there, the product is not.",
    source: "news", sourceName: "Fast Company", sourceUrl: "https://fastcompany.com",
    date: "2026-04-19", crossLinks: ["lon-s3"],
  },

  // ─── Spatial Computing ────────────────────────────────────────────────────
  {
    id: "spc-s1", trendId: "spatial-computing",
    title: "Vision Pro has sold 2M units in 18 months — fashion brands building experiences now get first-mover advantage",
    summary: "Vision Pro hit 2M units in 18 months — slower than iPhone but faster than iPad. The spatial app ecosystem is growing. Fashion brands building experiences now accumulate first-mover brand recall before the device reaches mass market.",
    source: "news", sourceName: "Bloomberg", sourceUrl: "https://bloomberg.com",
    date: "2026-05-21", crossLinks: ["did-s2", "arc-s2"],
  },
  {
    id: "spc-s2", trendId: "spatial-computing",
    title: "Net-a-Porter's Vision Pro app converts at 3x its standard app — presence and scale matter in spatial",
    summary: "Net-a-Porter's Vision Pro app lets users browse a life-size virtual boutique. Conversion rate is 3x their standard app — physical scale and immersion are proving to be decisive commercial advantages in spatial commerce.",
    source: "news", sourceName: "Vogue Business", sourceUrl: "https://voguebusiness.com",
    date: "2026-05-16", crossLinks: ["arc-s1", "arc-s5"],
  },
  {
    id: "spc-s3", trendId: "spatial-computing",
    title: "Cross-platform avatar standards are enabling a persistent digital self that follows you across all platforms",
    summary: "Open Metaverse ID and Ready Player Me are enabling a persistent digital self. Your digital identity follows you across games, apps, and workplaces — fashion becomes the expression layer of a permanent digital identity.",
    source: "hackernews", sourceName: "Hacker News", sourceUrl: "https://news.ycombinator.com",
    date: "2026-06-01", crossLinks: ["did-s4"],
  },
  {
    id: "spc-s4", trendId: "spatial-computing",
    title: "visionOS tutorials on YouTube are up 400% YoY — a new creator category of spatial experience designers is forming",
    summary: "A new creator category is emerging: spatial experience designers. YouTube tutorials on visionOS development are up 400% YoY — the talent pool for spatial brand experiences is forming, and the brands that engage it now will pay lower rates.",
    source: "youtube", sourceName: "YouTube", sourceUrl: "https://youtube.com",
    date: "2026-05-27", crossLinks: [],
  },
  {
    id: "spc-s5", trendId: "spatial-computing",
    title: "Vision Pro's community is split between power users building workflows and mainstream users returning devices",
    summary: "r/VisionPro shows a split community: power users building productive spatial workflows vs mainstream users returning devices. The use case gap is real — brand experiences that solve a genuine need, not just demonstrate novelty, will retain users.",
    source: "reddit", sourceName: "r/VisionPro", sourceUrl: "https://reddit.com/r/VisionPro",
    date: "2026-06-09", crossLinks: [],
  },
  {
    id: "spc-s6", trendId: "spatial-computing",
    title: "Samsung Galaxy XR at $999 means fashion brands must now design for two competing spatial platforms",
    summary: "Samsung's Android XR headset at $999 opens spatial computing to a broader audience. Fashion brands must now design for two competing spatial platforms simultaneously — doubling the creative and technical investment required.",
    source: "news", sourceName: "TechCrunch", sourceUrl: "https://techcrunch.com",
    date: "2026-05-29", crossLinks: ["arc-s2"],
  },
  {
    id: "spc-s7", trendId: "spatial-computing",
    title: "Decentraland Fashion Week 2026 drew 2M virtual attendees — Valentino and Diesel hosted spatial shows",
    summary: "Decentraland's 2026 Fashion Week drew 2M virtual attendees. Valentino and Diesel hosted spatial shows. The format is maturing from gimmick to genuine brand channel with meaningful reach numbers.",
    source: "news", sourceName: "Vogue Business", sourceUrl: "https://voguebusiness.com",
    date: "2026-03-25", crossLinks: ["did-s2", "spc-s1"],
  },
  {
    id: "spc-s8", trendId: "spatial-computing",
    title: "Dolby Atmos spatial audio is being layered onto fashion show recordings for immersive post-show Vision Pro experiences",
    summary: "Spatial audio is being layered onto fashion show recordings for Vision Pro — creating immersive front-row experiences available to anyone with a headset, anywhere, at any time. The fashion show is becoming a spatial media format.",
    source: "youtube", sourceName: "YouTube", sourceUrl: "https://youtube.com",
    date: "2026-04-30", crossLinks: [],
  },

  // ─── Longevity ────────────────────────────────────────────────────────────
  {
    id: "lon-s1", trendId: "longevity",
    title: "Bryan Johnson's extreme longevity protocol has spawned mass-market versions across supplements, beauty, and wearables",
    summary: "Bryan Johnson's $2M/year longevity protocol has spawned a mass-market version. Supplement brands, beauty lines, and wearable companies are all 'longevity' branding now — the concept has successfully crossed from extreme biohacking to mainstream consumer aspiration.",
    source: "news", sourceName: "Wired", sourceUrl: "https://wired.com",
    date: "2026-04-12", crossLinks: ["bio-s2", "wear-s1", "wear-s5"],
  },
  {
    id: "lon-s2", trendId: "longevity",
    title: "Senolytic compounds backed by peer-reviewed research are entering premium skincare formulation",
    summary: "Senolytic compounds (quercetin, fisetin) are entering premium skincare — backed by peer-reviewed research, not just marketing language. A new functional anti-ageing category is forming where clinical evidence is the minimum entry requirement.",
    source: "arxiv", sourceName: "arXiv", sourceUrl: "https://arxiv.org",
    date: "2026-05-04", crossLinks: ["bio-s1", "wear-s3"],
  },
  {
    id: "lon-s3", trendId: "longevity",
    title: "Longevity clinics offering NAD+ and epigenetic testing are opening in every major city — a new luxury health category",
    summary: "Longevity clinics offering NAD+ drips, epigenetic testing, and personalised protocols are opening in every major city. A $10B industry by 2028 — a new luxury health category sitting directly adjacent to fashion's premium consumer.",
    source: "news", sourceName: "Bloomberg", sourceUrl: "https://bloomberg.com",
    date: "2026-05-22", crossLinks: ["bio-s5", "neu-s1", "neu-s5"],
  },
  {
    id: "lon-s4", trendId: "longevity",
    title: "r/longevity has 400K members — a consumer longevity community that is demanding, literate, and brand-skeptical",
    summary: "r/longevity has 400K members discussing supplements, protocols, and research. This is consumer-driven longevity science — highly demanding, deeply literate, and deeply skeptical of marketing claims. Authenticity and clinical evidence are table stakes here.",
    source: "reddit", sourceName: "r/longevity", sourceUrl: "https://reddit.com/r/longevity",
    date: "2026-06-06", crossLinks: [],
  },
  {
    id: "lon-s5", trendId: "longevity",
    title: "Huberman, Attia, and Patrick have collectively surpassed fitness creators in YouTube views — longevity is the new wellness",
    summary: "Andrew Huberman, Peter Attia, and Rhonda Patrick have collectively surpassed traditional fitness creators in views. Longevity content is the new wellness genre — and its audience buys with higher income and more intentionally than the fitness audience.",
    source: "youtube", sourceName: "YouTube", sourceUrl: "https://youtube.com",
    date: "2026-05-13", crossLinks: [],
  },
  {
    id: "lon-s6", trendId: "longevity",
    title: "Off-label rapamycin prescriptions are up 400% at US longevity clinics — a transplant drug becoming a lifestyle supplement",
    summary: "Off-label rapamycin prescriptions for longevity are up 400% in US longevity clinics. A drug developed for transplant rejection is becoming a lifestyle supplement for the upper-middle class — the medicalisation of longevity is accelerating.",
    source: "arxiv", sourceName: "arXiv", sourceUrl: "https://arxiv.org",
    date: "2026-04-07", crossLinks: ["lon-s3"],
  },
  {
    id: "lon-s7", trendId: "longevity",
    title: "Biological age tests are available DTC for $200 — consumers are tracking biological vs chronological age",
    summary: "TruDiagnostic, Elysium, and similar biological age tests are now available DTC for $200. Consumers are tracking biological vs chronological age — a new performance metric that creates a clear hook for wellness and beauty brands.",
    source: "news", sourceName: "Bloomberg", sourceUrl: "https://bloomberg.com",
    date: "2026-05-01", crossLinks: ["wear-s1"],
  },
  {
    id: "lon-s8", trendId: "longevity",
    title: "500K cold plunge tubs have been sold — recovery culture has gone from biohacker niche to suburban backyard staple",
    summary: "Plunge and Polar Monkeys have sold 500K cold plunge tubs. From biohacker niche to suburban backyard staple in 18 months. Recovery culture is the new fitness culture — and it's reshaping how consumers think about health products.",
    source: "youtube", sourceName: "YouTube", sourceUrl: "https://youtube.com",
    date: "2026-05-19", crossLinks: ["neu-s1"],
  },
  {
    id: "lon-s9", trendId: "longevity",
    title: "VO2 max is the new status flex — being shared on social with the same weight as luxury goods",
    summary: "VO2 max scores are being shared on social media as health status signals. Apple Watch is adding VO2 max to watch faces. Fitness data is the new luxury flex — brands that can connect to this performance identity have a powerful positioning anchor.",
    source: "reddit", sourceName: "r/longevity", sourceUrl: "https://reddit.com/r/longevity",
    date: "2026-06-08", crossLinks: ["wear-s4"],
  },
  {
    id: "lon-s10", trendId: "longevity",
    title: "Ingestible collagen supplements are the fastest-growing beauty category — food is becoming the new skincare",
    summary: "Beauty-from-within collagen supplements are the fastest-growing beauty category. Vital Proteins (now Nestlé) signals that food is the new skincare — and the market will be $8B by 2027. The boundary between nutrition and beauty is dissolving.",
    source: "news", sourceName: "Business of Fashion", sourceUrl: "https://businessoffashion.com",
    date: "2026-04-23", crossLinks: ["bio-s6"],
  },
  {
    id: "lon-s11", trendId: "longevity",
    title: "NAD+ drip bars are opening next to concept stores in Milan, NYC, and Seoul",
    summary: "IV therapy and NAD+ drip bars are opening next to concept stores in fashion capitals. Luxury wellness experiences are becoming part of fashion retail neighbourhoods — a new kind of experiential retail adjacency forming.",
    source: "news", sourceName: "Vogue", sourceUrl: "https://vogue.com",
    date: "2026-05-08", crossLinks: ["lon-s3"],
  },
  {
    id: "lon-s12", trendId: "longevity",
    title: "Bakuchiol, HPR, and retinaldehyde are racing to replace retinol — a decade of market share is up for grabs",
    summary: "Bakuchiol, HPR, and retinaldehyde are competing to replace retinol. The skincare industry is in active ingredient upheaval — whoever wins the replacement race gets a decade of market share and reference position in millions of routines.",
    source: "news", sourceName: "Allure", sourceUrl: "https://allure.com",
    date: "2026-06-05", crossLinks: ["bio-s7"],
  },
  {
    id: "lon-s13", trendId: "longevity",
    title: "Content about centenarian lifestyles hits 300M views/month — Okinawa and Blue Zone habits are mainstream",
    summary: "Content following the daily routines of 100+ year-olds hits 300M views/month. Okinawan diet, Sardinian movement patterns, and Seventh-Day Adventist habits are now mainstream consumer topics — longevity is a cultural movement, not a health category.",
    source: "youtube", sourceName: "YouTube", sourceUrl: "https://youtube.com",
    date: "2026-06-01", crossLinks: [],
  },
];

export function computeLayout(): {
  trends: (Trend & { radius: number })[];
  signalPositions: Map<string, { x: number; y: number }>;
} {
  const MIN_RADIUS = 55;
  const MAX_RADIUS = 110;
  const ORBIT_PADDING = 200;
  const SIGNAL_W = 190;
  const SIGNAL_H = 64;

  const signalPositions = new Map<string, { x: number; y: number }>();
  const trends = TRENDS.map((t) => {
    const radius = MIN_RADIUS + (t.relevanceScore / 100) * (MAX_RADIUS - MIN_RADIUS);
    const signals = SIGNALS.filter((s) => s.trendId === t.id);
    const orbitRadius = radius + ORBIT_PADDING;
    signals.forEach((sig, i) => {
      const angle = (2 * Math.PI * i) / signals.length - Math.PI / 2;
      const x = t.position.x + orbitRadius * Math.cos(angle) - SIGNAL_W / 2;
      const y = t.position.y + orbitRadius * Math.sin(angle) - SIGNAL_H / 2;
      signalPositions.set(sig.id, { x, y });
    });
    return { ...t, radius };
  });

  return { trends, signalPositions };
}

export function getSourceIcon(source: Signal["source"]): string {
  return {
    reddit: "🔴",
    news: "📰",
    youtube: "▶️",
    arxiv: "🔬",
    hackernews: "🟠",
    manual: "✦",
  }[source ?? "manual"] ?? "✦";
}
