"use client";

import { useState } from "react";
import { Trend, Signal } from "@/types";
import { SIGNALS, getSourceIcon } from "@/lib/trends";

interface Props {
  trend: Trend & { radius: number };
  onClose: () => void;
  loading?: boolean;
}

function buildReport(trend: Trend, signals: Signal[]): string {
  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  return `# ${trend.name}
*Trend Intelligence Report · ${date}*

---

## Overview

${trend.description}

**Cultural Relevance Score: ${trend.relevanceScore}/100**

---

## Signal Evidence (${signals.length} signals)

${signals.map((s) => `### ${s.title}
**Source:** ${s.sourceName ?? "—"} · ${s.date ? new Date(s.date).toLocaleDateString("en-US", { month: "short", year: "numeric" }) : ""}

${s.summary}
`).join("\n")}

---

## Cross-Trend Connections

${[...new Set(signals.flatMap((s) => (s.crossLinks ?? [])))].length > 0
  ? "This trend connects to signals in adjacent categories — see canvas for full cross-connections."
  : "No cross-trend connections identified yet."}

---

*Generated by Rarity Radar*`.trim();
}

export function TrendPanel({ trend, onClose, loading }: Props) {
  const [showFull, setShowFull] = useState(false);
  const signals = SIGNALS.filter((s) => s.trendId === trend.id);
  const crossCount = new Set(signals.flatMap((s) => (s.crossLinks ?? []))).size;

  const download = () => {
    const content = buildReport(trend, signals);
    const blob = new Blob([content], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `${trend.id}-report.md`;
    a.click();
  };

  return (
    <div style={{
      position: "fixed",
      right: 0,
      top: 0,
      height: "100%",
      width: 420,
      backgroundColor: "#0e0e0e",
      borderLeft: "1px solid #222",
      boxShadow: "-32px 0 80px rgba(0,0,0,0.8)",
      zIndex: 40,
      display: "flex",
      flexDirection: "column",
      fontFamily: "'DM Sans', sans-serif",
    }}>
      {/* Top color bar */}
      <div style={{ height: 4, background: `linear-gradient(90deg, ${trend.color}, ${trend.color}44, transparent)`, flexShrink: 0 }} />

      {/* Header */}
      <div style={{ padding: "24px 28px 20px", borderBottom: "1px solid #1e1e1e", flexShrink: 0 }}>
        <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 12 }}>
          <div style={{ flex: 1 }}>
            {loading && (
              <div style={{ fontSize: 10, color: "#444", marginBottom: 8, fontWeight: 600, letterSpacing: "0.06em", textTransform: "uppercase" }}>
                Fetching live score…
              </div>
            )}
            <h2 style={{
              fontFamily: "'DM Serif Display', serif",
              fontSize: 20,
              fontWeight: 400,
              color: "#f0ede8",
              lineHeight: 1.2,
              letterSpacing: "-0.02em",
              marginBottom: 14,
            }}>
              {trend.name}
            </h2>

            {/* Relevance bar */}
            <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
              <div style={{ flex: 1, height: 3, backgroundColor: "#1e1e1e", borderRadius: 2, overflow: "hidden" }}>
                <div style={{ width: `${trend.relevanceScore}%`, height: "100%", backgroundColor: trend.color, borderRadius: 2 }} />
              </div>
              <span style={{ fontSize: 11, color: "#555", fontWeight: 600, whiteSpace: "nowrap" }}>
                {trend.relevanceScore}% cultural relevance
              </span>
            </div>
          </div>
          <button
            onClick={onClose}
            style={{ color: "#333", fontSize: 22, lineHeight: 1, background: "none", border: "none", cursor: "pointer", padding: 0, marginTop: 2 }}
          >
            ×
          </button>
        </div>

        <p style={{ fontSize: 13, color: "#666", lineHeight: 1.65, marginTop: 14 }}>
          {trend.description}
        </p>

        <div style={{ display: "flex", gap: 16, marginTop: 14, fontSize: 11, color: "#444", fontWeight: 600 }}>
          <span>{signals.length} signals</span>
          {crossCount > 0 && <span>· {crossCount} cross-connections</span>}
        </div>
      </div>

      {/* Body */}
      <div style={{ flex: 1, overflowY: "auto", padding: "20px 28px" }}>
        {!showFull ? (
          <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
            <div style={{ fontSize: 9, fontWeight: 700, color: "#333", textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: 4 }}>
              Signal evidence
            </div>
            {signals.map((s) => (
              <div key={s.id} style={{
                backgroundColor: "#141414",
                border: "1px solid #1e1e1e",
                borderLeft: `3px solid ${trend.color}`,
                borderRadius: 10,
                padding: "12px 14px",
              }}>
                <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 6 }}>
                  <span style={{ fontSize: 11 }}>{getSourceIcon(s.source)}</span>
                  <span style={{ fontSize: 9, color: trend.color, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.07em" }}>
                    {s.sourceName}
                  </span>
                  <span style={{ marginLeft: "auto", fontSize: 9, color: "#333" }}>
                    {s.date ? new Date(s.date).toLocaleDateString("en-US", { month: "short", day: "numeric" }) : ""}
                  </span>
                </div>
                <div style={{ fontSize: 12, fontWeight: 600, color: "#d0ccc8", lineHeight: 1.35, marginBottom: 5 }}>{s.title}</div>
                <div style={{ fontSize: 11, color: "#555", lineHeight: 1.55 }}>{s.summary}</div>
                {(s.crossLinks ?? []).length > 0 && (
                  <div style={{ marginTop: 8, fontSize: 10, color: "#444", fontWeight: 600 }}>
                    ↔ {(s.crossLinks ?? []).length} cross-trend link{(s.crossLinks ?? []).length > 1 ? "s" : ""}
                  </div>
                )}
              </div>
            ))}
          </div>
        ) : (
          <div style={{ fontSize: 12, color: "#777", lineHeight: 1.8 }}>
            <div style={{ fontSize: 9, fontWeight: 700, color: "#333", textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: 16 }}>
              Full report
            </div>
            {buildReport(trend, signals).split("\n").map((line, i) => {
              if (line.startsWith("# ")) return <h2 key={i} style={{ fontFamily: "'DM Serif Display', serif", fontSize: 20, color: "#e8e4df", marginTop: 0, marginBottom: 8, fontWeight: 400 }}>{line.slice(2)}</h2>;
              if (line.startsWith("## ")) return <h3 key={i} style={{ fontSize: 11, fontWeight: 700, color: "#444", textTransform: "uppercase", letterSpacing: "0.08em", marginTop: 24, marginBottom: 10, paddingTop: 16, borderTop: "1px solid #1e1e1e" }}>{line.slice(3)}</h3>;
              if (line.startsWith("### ")) return <h4 key={i} style={{ fontSize: 12, fontWeight: 600, color: "#aaa", marginTop: 16, marginBottom: 4 }}>{line.slice(4)}</h4>;
              if (line.startsWith("---")) return <div key={i} style={{ borderTop: "1px solid #1e1e1e", margin: "16px 0" }} />;
              if (!line.trim()) return <div key={i} style={{ height: 4 }} />;
              return <p key={i} style={{ margin: "2px 0", fontSize: 12, color: "#666" }}>{line}</p>;
            })}
          </div>
        )}
      </div>

      {/* Footer */}
      <div style={{ padding: "16px 28px", borderTop: "1px solid #1a1a1a", display: "flex", gap: 10, flexShrink: 0 }}>
        <button
          onClick={() => setShowFull((v) => !v)}
          style={{
            flex: 1, padding: "11px 0",
            border: "1px solid #2a2a2a", borderRadius: 10,
            fontSize: 12, fontWeight: 600, color: "#666",
            background: "transparent", cursor: "pointer",
            fontFamily: "'DM Sans', sans-serif",
          }}
        >
          {showFull ? "← Summary" : "Full report"}
        </button>
        <button
          onClick={download}
          style={{
            flex: 1, padding: "11px 0",
            border: "none", borderRadius: 10,
            fontSize: 12, fontWeight: 700,
            color: "#000", backgroundColor: trend.color,
            cursor: "pointer", fontFamily: "'DM Sans', sans-serif",
            boxShadow: `0 0 20px ${trend.color}55`,
          }}
        >
          Export .md
        </button>
      </div>
    </div>
  );
}
