"use client";

import { useState } from "react";
import { Trend, Signal } from "@/types";
import { SIGNALS, getSourceIcon } from "@/lib/trends";

interface Props {
  trend: Trend & { radius: number };
  onClose: () => void;
  loading?: boolean;
}

function buildReport(trend: Trend, signals: Signal[]): string {
  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  return `# ${trend.name}
*Trend Intelligence Report · ${date}*

---

## Overview

${trend.description}

**Cultural Relevance Score: ${trend.relevanceScore}/100**

---

## Signal Evidence (${signals.length} signals)

${signals.map((s) => `### ${s.title}
**Source:** ${s.sourceName ?? "—"} · ${s.date ? new Date(s.date).toLocaleDateString("en-US", { month: "short", year: "numeric" }) : ""}

${s.summary}
`).join("\n")}

---

## Cross-Trend Connections

${[...new Set(signals.flatMap((s) => s.crossLinks))].length > 0
  ? "This trend connects to signals in adjacent categories — see canvas for full cross-connections."
  : "No cross-trend connections identified yet."}

---

*Generated by Trend Radar*`.trim();
}

export function TrendPanel({ trend, onClose, loading }: Props) {
  const [showFull, setShowFull] = useState(false);
  const signals = SIGNALS.filter((s) => s.trendId === trend.id);
  const crossCount = new Set(signals.flatMap((s) => s.crossLinks)).size;

  const download = () => {
    const content = buildReport(trend, signals);
    const blob = new Blob([content], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `${trend.id}-report.md`;
    a.click();
  };

  return (
    <div className="fixed right-0 top-0 h-full w-[420px] bg-white border-l border-gray-100 shadow-2xl z-40 flex flex-col">
      {/* Header */}
      <div className="px-6 py-5 border-b border-gray-100 flex-shrink-0" style={{ borderTop: `4px solid ${trend.color}` }}>
        <div className="flex items-start justify-between gap-3">
          <div>
            <h2 className="font-bold text-gray-900 text-base leading-snug">{trend.name}</h2>
            {loading && <div className="text-xs text-gray-400 animate-pulse mt-1">Fetching live score…</div>}
          <div className="flex items-center gap-2 mt-1.5">
              <div className="h-1.5 rounded-full bg-gray-100 w-24 overflow-hidden">
                <div
                  className="h-full rounded-full"
                  style={{ width: `${trend.relevanceScore}%`, backgroundColor: trend.color }}
                />
              </div>
              <span className="text-xs text-gray-400 font-medium">{trend.relevanceScore}% relevance</span>
            </div>
          </div>
          <button onClick={onClose} className="text-gray-300 hover:text-gray-600 text-xl leading-none mt-0.5">×</button>
        </div>
        <p className="text-sm text-gray-500 leading-relaxed mt-3">{trend.description}</p>
        <div className="flex items-center gap-3 mt-3 text-xs text-gray-400">
          <span>{signals.length} signals</span>
          {crossCount > 0 && <span>· {crossCount} cross-connections</span>}
        </div>
      </div>

      {/* Signals list */}
      <div className="flex-1 overflow-y-auto px-6 py-4 space-y-3">
        {!showFull ? (
          <>
            {/* Summary view */}
            <div className="text-xs font-semibold text-gray-400 uppercase tracking-widest mb-3">Signal evidence</div>
            {signals.map((s) => (
              <div key={s.id} className="bg-gray-50 rounded-xl p-4 border border-gray-100">
                <div className="flex items-center gap-2 mb-1.5">
                  <span className="text-sm">{getSourceIcon(s.source)}</span>
                  <span className="text-xs text-gray-400 font-medium">{s.sourceName}</span>
                  <span className="text-xs text-gray-300 ml-auto">
                    {s.date ? new Date(s.date).toLocaleDateString("en-US", { month: "short", day: "numeric" }) : ""}
                  </span>
                </div>
                <div className="text-xs font-semibold text-gray-800 mb-1 leading-snug">{s.title}</div>
                <div className="text-xs text-gray-500 leading-relaxed line-clamp-2">{s.summary}</div>
                {(s.crossLinks ?? []).length > 0 && (
                  <div className="mt-2 text-xs text-indigo-400 font-medium">
                    ↔ {(s.crossLinks ?? []).length} cross-trend link{(s.crossLinks ?? []).length > 1 ? "s" : ""}
                  </div>
                )}
              </div>
            ))}
          </>
        ) : (
          /* Full report view */
          <div className="prose prose-sm max-w-none text-sm text-gray-700 leading-relaxed">
            <div className="text-xs font-semibold text-gray-400 uppercase tracking-widest mb-3">Full report</div>
            {buildReport(trend, signals).split("\n").map((line, i) => {
              if (line.startsWith("# ")) return <h2 key={i} className="text-base font-bold text-gray-900 mt-4 mb-1">{line.slice(2)}</h2>;
              if (line.startsWith("## ")) return <h3 key={i} className="text-sm font-bold text-gray-800 mt-5 mb-2 pt-3 border-t border-gray-100">{line.slice(3)}</h3>;
              if (line.startsWith("### ")) return <h4 key={i} className="text-xs font-bold text-gray-700 mt-3 mb-1">{line.slice(4)}</h4>;
              if (line.startsWith("**") && line.endsWith("**")) return <p key={i} className="font-semibold text-gray-800 my-1 text-xs">{line.slice(2,-2)}</p>;
              if (line.startsWith("---")) return <hr key={i} className="my-3 border-gray-100" />;
              if (!line.trim()) return <div key={i} className="h-1" />;
              return <p key={i} className="text-xs text-gray-600 my-1">{line}</p>;
            })}
          </div>
        )}
      </div>

      {/* Footer */}
      <div className="px-6 py-4 border-t border-gray-100 flex gap-2 flex-shrink-0">
        <button
          onClick={() => setShowFull((v) => !v)}
          className="flex-1 py-2.5 border border-gray-200 rounded-xl text-xs font-semibold text-gray-700 hover:bg-gray-50 transition-colors"
        >
          {showFull ? "← Summary" : "Full report"}
        </button>
        <button
          onClick={download}
          className="flex-1 py-2.5 text-white rounded-xl text-xs font-semibold transition-colors"
          style={{ backgroundColor: trend.color }}
        >
          Export .md
        </button>
      </div>
    </div>
  );
}
